### ISSUE TITLE
Stack image does no cleanup between runs

### ISSUE THREAD

**Issue by fizruk** [commercialhaskell/stack#1014]
Changing `add` field in `stack.yaml` for `stack image` or files in those directories does not reset `.stack-work/image/` directory.
This results may result in
- image having files from previous `stack image container` runs;
- errors if previously created directory name is now used for a file.

Steps to reproduce (any stack project):

1. Create directory with a file in it:

    ```
    $ mkdir static
    $ touch static/run.sh
    ```

2. Add `image` section to `stack.yaml`:

    ```yaml
    ...
    image:
      container:
        # you can use any base image, this one is just small
        base: phusion/baseimage:0.9.17
        add:
          static: /etc/static
    ```

3. Run `stack image container`.
4. Look at `.stack-work/image/etc/static`:

    ```
    $ ls .stack-work/image/etc/static
    run.sh
    ```
5. Now edit the `static/` directory:

    ```
    $ mkdir static/run
    $ mv static/run.sh static/run/run.sh
    ```

6. Run `stack image container`.
7. Look at `.stack-work/image/etc/static`:

    ```
    $ ls .stack-work/image/etc/static
    run/ run.sh
    ```

    **The `run.sh` file from the previous run has not been deleted!**

8. Edit the `static/` directory once more:

    ```
    $ mv static/run/run.sh static/run.sh
    $ rmdir static/run
    $ mv static/run.sh static/run
    ```

9. Run `stack image container`:

    ```
    $ stack image container
    /root/temp/<project>/.stack-work/image/etc/static/run: copyFile: inappropriate type (is a directory)
    ```

   **The `static/run/` directory from the previous run has not been deleted!**
