### ISSUE TITLE
stack fails to install stack-ide

### ISSUE THREAD

**Issue by LukeHoersten** [commercialhaskell/stack#1037]
Global `stack.yaml`:
```yaml
resolver: lts-3.5
packages:
  - location:
      git: git@github.com:commercialhaskell/stack-ide
      commit: bd7d845aa1654bca59a87aed44860c7b0e436031
    extra-dep: true
    subdirs:
      - stack-ide
      - stack-ide-api
```

```
$ stack install stack-ide
Run from outside a project, using implicit global config
Using resolver: lts-3.5 from global config file: /Users/luke/.stack/global/stack.yaml
happy-1.19.5: copying precompiled package
Progress: 1/6/Users/luke/.stack/snapshots/x86_64-osx/lts-3.5/7.10.2/bin/: copyFile: inappropriate type (is a directory)
```

Then fails to install.
