### ISSUE TITLE
Allow to pull extra-deps from other resolvers

### ISSUE THREAD

**Issue by zudov** [commercialhaskell/stack#1175]
It's often that a project uses an resolver `x` but also needs some dependencies which aren't in the `x` (but are in the `y`, or `z`). At the moment the only option is to just specify it in `extra-deps` with an explicit version. It would be nice if it was possible to pull them from some other resolver.

This syntax comes to mind (and would probably explain the intention better than text above):

``` yaml
- resolver: lts-3.9
- deps:
  - extra: # same as current `extra-deps`
    - package-which-isnt-present-in-any-of-resolvers-0.1.2.3
  - nightly-2015-10-16:
    - package-which-is-present-in-nightly
```

`package-which-is-present-in-nightly` doesn't need to contain an explicit version, it would just pick up the one from `nightly-2015-10-16`.

**Comment by borsboom** [comment]
I'm a bit unclear on what concrete benefit this would really provide.  Is it so hard to provide the exact version number in this case?

**Comment by zudov** [comment]
Let's imagine a situation where we use `lts` resolver, but want some other dependencies which are not present in `lts` but are in the `nightly`. Currently we end up with something like that:

```yaml
extra-deps:
  - distributed-process-0.5.5.1
  - distributed-process-async-0.2.2
  - distributed-process-client-server-0.1.3.1
  - distributed-process-execution-0.1.2.1
  - ... many more
```

When I add those `extra-deps`, I don't have much guarantees that they would work fine with my project. However, if I pick the same versions as in the latest  `nightly` release I can get the guarantee that they would at least compile against each other. So for every item in `extra-deps` I have to (1) check the version in some nightly release; (2) put that version in my extra-deps. I'd much rather just write:

```yaml
- deps:
  - nightly-2015-10-16:
    - distributed-process
    - distributed-process-async
```

Now, let's imagine that some time passed and I want to bump these versions, now I would have to again open the stackage page of the latest resolver and check a version of every package that I have in my `extra-deps`. I would much rather prefer to do:

```diff
-    - nightly-2015-10-16
+    - nightly-2015-10-22
```
