### ISSUE TITLE
Stack should be more clear about packages vs. dependencies

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#1217]
I realize it may be convenient, but including two different kinds of things under the header of "packages", where `extra-dep: true` flips the switch from one default to the other is possibly counter-productive from a UX point of view. I just helped another Stack user who is _quite_ comfortable with Haskell and Cabal get unstuck because their `stack ghci` was broken. It was broken because they had intended to add local/git repos as additional dependencies, but didn't know they needed `extra-dep: true` to make them not be primary targets of the Stack build environment.

The documentation does touch on this, but doesn't exactly come right out and say it, and honestly, I think getting people to read the docs before diving in is going to be a bit hard as Stack is easy enough to use that they won't really ever need to pause until they run into a problem.

I think a more lasting solution is having separate top-level stanzas for build targets and dependencies coming from a filepath or git repository. The overlap of attributes for these is possibly galling, but you could console yourself with the idea that this is a sum-of-products representation :)

Another issue is the word packages itself. This is sort of a "bring your own preconceptions" word where to some it means "build target" and others it means "dependency you install". I think this is intentional in order to make it a catch-all, but doesn't help with the clarity issue here.

**Comment by mgsloan** [comment]
How about having `extra-deps` take the [same format as `packages`](https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md#packages)?  Except instead of taking `some_directory`, it would expect the `package-version` info currently used by `extra-deps`.

**Comment by bitemyapp** [comment]
@mgsloan I've spent a good 5 minutes puzzling over what you mean, could you write some strawman yaml to demonstrate what you have in mind?

**Comment by mgsloan** [comment]
@bitemyapp Sorry for the confusion, I was being overly terse.  What I mean is that the `extra-dep: true` flag seems very ugly to me.  extra-deps should be in the extra-deps list, local packages should be in the packages list.

Taking an example from https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md#packages : 

```yaml
packages:
- local-package
- location: vendor/binary
  extra-dep: true
- location:
    git: git@github.com:yesodweb/wai
    commit: 2f8a8e1b771829f4a8a77c0111352ce45a14c30f
  subdirs:
  - auto-update
  - wai
```

Would instead be written

```yaml
packages:
- local-package
- location:
    git: git@github.com:yesodweb/wai
    commit: 2f8a8e1b771829f4a8a77c0111352ce45a14c30f
  subdirs:
  - auto-update
  - wai
extra-deps:
- location: vendor/binary
```

This does not solve the issue of the user not understanding deps vs local packages, but I think it's much cleaner.

**Comment by bitemyapp** [comment]
>However, extra-deps will need to have strings parsed as a package + version, whereas packages have string parsed as a directory.

Perhaps trying to avoid syntactic overlap was part of the motivation for this? I'm planning to make a video tutorial for Slack with my coauthor soon, so perhaps at least that could help.

It seems like it might be more clear, but I'm not convinced the change would be worth the breakage. I'll stew on it. Please pipe up if you have any ideas.

**Comment by mgsloan** [comment]
To soften the breakage, we can certainly have a deprecation of a few major versions.

**Comment by bitemyapp** [comment]
It might seem petty, but perhaps projects rather than packages would make it more clear? I don't think most programmers are accustomed to thinking of packages as anything but dependencies.

```yaml
projects:
- local-project
- location:
    git: git@github.com:yesodweb/wai
    commit: 2f8a8e1b771829f4a8a77c0111352ce45a14c30f
  subdirs:
  - auto-update
  - wai
dependencies:
- location: vendor/binary
```
