### ISSUE TITLE
Extra dep specified as git repo builds unnecessarily

### ISSUE THREAD

**Issue by chreekat** [commercialhaskell/stack#1295]
On current HEAD of [Snowdrift's](https://github.com/snowdriftcoop/snowdrift) master  (ad236659f819eb220c282f35a4b04525a9fdc52b), the dependency ghci-runner is rebuilt after a 'stack clean':

```
$ stack clean
$ stack build
Snowdrift-0.1.4: unregistering (missing dependencies: ghci-runner)
ghci-runner-0.0.0.0: unregistering (local file changes: ghci-runner.cabal src/Dev/Runner.hs)
ghci-runner-0.0.0.0: configure
ghci-runner-0.0.0.0: build
ghci-runner-0.0.0.0: copy/register
Snowdrift-0.1.4: configure
Configuring Snowdrift-0.1.4...
```

Is this intended behavior?

If not, is this because both Snowdrift and ghci-runner have a source file 'src/Dev/Runner.hs'? But then why does it say that ghci-runner.cabal changes, too?

The [stack.yaml](https://github.com/snowdriftcoop/snowdrift/blob/ad236659f819eb220c282f35a4b04525a9fdc52b/stack.yaml):

```
packages:
- '.'
- location:
    git: https://github.com/chreekat/ghci-runner.git
    commit: bae5a558535087c8cc532da0fd192625361d8a25
  extra-dep: true
```
