### ISSUE TITLE
docker with git repos

### ISSUE THREAD

**Issue by gregwebs** [commercialhaskell/stack#1358]
I have only seen 1 issue after taking advantage of #531, usage with git repos

I get errors when I have a config like this with `docker:` in it also.

```
packages:
  - .
  - extra-dep: true
  - location:
      git: ...
      subdirs: ...
```

When I remove the `docker:` section everything installs.
It seems that I need to mount my `~/.ssh` directory, but I cannot figure out how to get that to work.
