### ISSUE TITLE
Question: config.yaml with configuration fails to parse.

### ISSUE THREAD

**Issue by VitorCBSB** [commercialhaskell/stack#1400]
Hey, sorry if this is not the ideal place to ask this, but I have been having trouble inserting default template information in the global config.yaml file. The following fails to parse:

```
# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md
#
templates:
  params:
    author-name: Vitor
    author-email: Removed
    category: Experimental
    copyright: Copyright: (c) 2015 Vitor
    github-username: VitorCBSB
```

while doing a ```stack new Test simple``` with the following error:

```
Could not parse 'C:\stack_root\config.yaml':
InvalidYaml (Just (YamlParseException {yamlProblem = "mapping values are not allowed in this context", yamlContext = "", yamlProblemMark = YamlMark {yamlIndex = 363, yamlLine = 9, yamlColumn = 24}}))
See https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md.
```

I'm just wondering if I'm doing a stupid mistake, I have no idea where to ask so I'm asking here.

EDIT: Oh yes, current stack version:
```
C:\Users\Vitor Coimbra>stack --version
Version 0.1.8.0, Git revision 52bb19764e20a4433f3f8c65e4093d2a51568c00 (2602 commits) x86_64
```
