### ISSUE TITLE
priority of flags : shouldn't command-line arguments take precedence over stack.yaml file 

### ISSUE THREAD

**Issue by nrolland** [commercialhaskell/stack#1414]
Twitter-conduit has a flag `build-samples` in its cabal file and doesn't use stack

When I generate the stack girl with stack init, it copies over flags in the project and write in stack.yam
```
# Override default flag values for local packages and extra-deps
flags:
  twitter-conduit:
    lens-aeson: true
    build-samples: false
    network-uri: true
    run-integrated-test: false
```

Now when I launch `stack build --flag twitter-conduit:build-samples` the setting in stack.yaml file takes precedence, whereas I would have expected the command line argument to do so.

not sure it's a wanted behavior or not.
