### ISSUE TITLE
Setup-info URL parsing too restrictive

### ISSUE THREAD

**Issue by 3noch** [commercialhaskell/stack#1440]
If you want to download GHCJS from GitHub you could potentially do something like:

```
compiler: ghcjs-0.2.0.20151106_ghc-7.10.2
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20151106_ghc-7.10.2:
        url: "https://github.com/ghcjs/ghcjs/tarball/561365ba1667053b5dc5846e2a8edb33eaa3f6dd"
```

But the `url` does not end with `.tar.gz` so `stack` can't figure out what to with it. This seems like a silly problem to have. Stack could inspect the content-type from the server or just let the yaml file describe the archive type.
