### ISSUE TITLE
stack build does not recognize the package

### ISSUE THREAD

**Issue by gregwebs** [commercialhaskell/stack#163]
I have a cabal file in a directory. When I run `stack build` I get a `stack.yaml` of

```
flags:
  load-data:
    production: false
packages: []
extra-deps: []
resolver: lts-2.11
```

Note that `packages` does not include `"."`. If I add that in manually, everything works.
