### ISSUE TITLE
ghc-options get applied to extra-dep packages from git

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1631]
See https://github.com/haskell/haskell-ide-engine/pull/165#issuecomment-170285974 .  The issue is that `ghc-options` get applied to a package like this

```yaml
- location:
    git: https://github.com/kazu-yamamoto/ghc-mod.git
    commit: b9bd4ebf77b22d2d9061d647d7799ddcc7c51228
  extra-dep: true
```

Even though `apply-ghc-options` is its default value, `local`.
