### ISSUE TITLE
Support release candidates in "ghc only" resolvers

### ISSUE THREAD

**Issue by zudov** [commercialhaskell/stack#1651]
It would be nice if stack provided a simple way to try out the GHC's release candidates.

**Steps to reproduce**:

```
stack --resolver ghc-8.0.1-rc1 setup
```

**Expected**:
Stack would download and install the release candidate.

**Actual result**:

```
option --resolver: Invalid resolver value: ghc-8.0.1-rc1. Possible valid values include lts-2.12, nightly-YYYY-MM-DD, ghc-7.10.2, and ghcjs-0.1.0_ghc-7.10.2. See https://www.stackage.org/snapshots for a complete list.
```

**Comment by mgsloan** [comment]
Hi!  This is a reasonable idea, but I wonder if we want to clutter up [stack-setup-2.yaml](https://github.com/fpco/stackage-content/blob/master/stack/stack-setup-2.yaml) with release candidates.  Maybe by removing them as newer versions of 8.0 are released?

In the meantime, you can have stack setup RC versions by adding a setup-info to your `stack.yaml`.  Here's what I'm using for my 64 bit linux install:

```
compiler: ghc-8.0.0.20160111
setup-info:
  ghc:
    linux64:
      8.0.0.20160111:
        url: "http://downloads.haskell.org/~ghc/8.0.1-rc1/ghc-8.0.0.20160111-x86_64-deb7-linux.tar.xz"
        content-length: 111404852
        sha1: 30d39c6ca6994dcafe25595e053035ad23198b52
```

(the `content-length` and `sha1` fields are optional)
