### ISSUE TITLE
`stack ghci` does not include `extra-lib-dirs` from yaml configuration

### ISSUE THREAD

**Issue by luigy** [commercialhaskell/stack#1656]
and also probably applies to `extra-include-dirs`
assuming that the library and headers exists at the locations listed in the yaml configuration

Expected:
```
> stack ghci
...
Configuring GHCi with the following packages: leveldb-haskell
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
...
Ok, modules loaded: Database.LevelDB, Database.LevelDB.Base, Database.LevelDB.C, Database.LevelDB.Internal, Database.LevelDB.Iterator, Database.LevelDB.MonadResource, Database.LevelDB.Streaming, Database.LevelDB.Types, Data.Stream.Monadic.
*Data.Stream.Monadic Data.Stream.Monadic Database.LevelDB Database.LevelDB.Base Database.LevelDB.C Database.LevelDB.Internal Database.LevelDB.Iterator Database.LevelDB.MonadResource Database.LevelDB.Streaming Database.LevelDB.Types>
```

Actual:
```
> stack ghci
...
Configuring GHCi with the following packages: leveldb-haskell
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
<command line>: user specified .o/.so/.DLL could not be loaded (dlopen(libleveldb.dylib, 5): image not found)
Whilst trying to load:  (dynamic) leveldb
Additional directories searched: (none)
```

stack.yaml
```yaml
# /Users/luigy/code/haskell/stack-issues/leveldb-haskell-0.6.3/stack.yaml
resolver: lts-4.1
packages:
- '.'

extra-include-dirs:
  - /Users/luigy/code/haskell/stack-issues/leveldb-haskell-0.6.3/leveldb/include
extra-lib-dirs:
  - /Users/luigy/code/haskell/stack-issues/leveldb-haskell-0.6.3/leveldb
```

```
> stack --version
Version 1.0.1, Git revision 19f00be8bcb6e891f7f627ce3e1164eaa7be19b1 (dirty) (3073 commits) x86_64
```
