### ISSUE TITLE
Stack + Nix + MacOS: 'CoreServices/CoreServices.h' file not found

### ISSUE THREAD

**Issue by lippling** [commercialhaskell/stack#1698]
I'm using `stack 1.0.2 x86_64` and this `stack.yaml`:

```
flags: {}
packages:
- '.'
extra-deps:
- imagemagick-0.0.3.5
resolver: lts-3.20
nix:
    enable: true
    packages:
    - zlib
    - imagemagick
    - pkgconfig
```

When I run `stack build` I get:

```
Configuring hfsevents-0.1.6...
Building hfsevents-0.1.6...
Preprocessing library hfsevents-0.1.6...
[1 of 1] Compiling System.OSX.FSEvents ( System/OSX/FSEvents.hs, .stack-work/dist/x86_64-osx-nix/Cabal-1.22.4.0/build/System/OSX/FSEvents.o )

cbits/c_fsevents.m:1:10:
     fatal error: 'CoreServices/CoreServices.h' file not found
#include <CoreServices/CoreServices.h>
         ^
1 error generated.
```

Do I have to include the system frameworks somehow?
