### ISSUE TITLE
Stack with GHC 8

### ISSUE THREAD

**Issue by fizruk** [commercialhaskell/stack#1757]
I am trying this config on Mac OS X (El Capitan):

```yaml
resolver: lts-5.0
compiler: ghc-8.0.1
packages:
- '.'
extra-deps: []
flags: {}
extra-package-dbs: []

setup-info:
  ghc:
    macosx:
      8.0.1:
        url: "http://downloads.haskell.org/~ghc/8.0.1-rc2/ghc-8.0.0.20160204-x86_64-apple-darwin.tar.xz"
```

And get this error:

```
$ stack setup
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
No sha1 found in metadata, download hash won't be checked.
Already downloaded.
Configuring GHC ...Did not find executable at specified path: /private/var/folders/d5/t52r7rc52nn5_vghhfz27v9w0000gn/T/stack-setup70995/ghc-8.0.1/configure
```

I suspect something changed within GHC distribution.
If this is inappropriate place for this issue, please redirect me to one.

**Comment by borsboom** [comment]
I haven't looked at the bindist (on a slow connection) but the top-level directory of the bindist tarball has to match the version number.  So you mean need to specify version `8.0.0.20160204` if that's the name of the directory instead of `8.0.1`.

**Comment by fizruk** [comment]
@borsboom thanks that worked!

Now I need to figure out custom snapshot I guess.

**Comment by fizruk** [comment]
For the sake of history, this is the config that worked for me: https://gist.github.com/fizruk/a203aecee813ef513aec

**Comment by k-bx** [comment]
@fizruk @borsboom I'm trying to do something very similar but for linux to test my project with GHC8, but fail.

snapshot-ghc8.yaml:

```
compiler: ghc-8.0.0.20160204
setup-info:
  ghc:
    linux64:
      8.0.0.20160204:
        url: "http://downloads.haskell.org/~ghc/8.0.1-rc2/ghc-8.0.0.20160204-x86_64-deb8-linux.tar.xz"

packages:
  - abstract-deque-0.3
  - abstract-par-0.3.3
  - AC-Vector-2.3.2
  - accelerate-0.15.1.0
  - ace-0.6
...
```

stack.yaml:

```
resolver:
  location: snapshot-ghc8.yaml
  name: snapshot-ghc8

packages:
...
```

Running `stack setup`:

```
kb@kb-vaio:~/workspace/proj$ stack setup
Caching build plan
No information found for ghc-8.0.0.20160204.
Supported versions for OS key 'linux64': GhcVersion 7.8.4, GhcVersion 7.10.1, GhcVersion 7.10.2, GhcVersion 7.10.3
```

Did you see something similar? Thanks.
