### ISSUE TITLE
Invalid package ID with GHC 8

### ISSUE THREAD

**Issue by fizruk** [commercialhaskell/stack#1758]
I have this custom snapshot:

```yaml
# snapshot-ghc8.yaml
compiler: ghc-8.0.0.20160204

setup-info:
  ghc:
    macosx:
      8.0.0.20160204:
        url: "http://downloads.haskell.org/~ghc/8.0.1-rc2/ghc-8.0.0.20160204-x86_64-apple-darwin.tar.xz"

packages: []
```

And this config:

```yaml
resolver:
  location: snapshot-ghc8.yaml
  name: snapshot-ghc8
packages:
- '.'
extra-deps: []
flags: {}
extra-package-dbs: []
```

I get this error when trying to build anything:

```
$ stack build
Caching build plan
Invalid package ID: "array-0.5.1.0 base-4.9.0.0 binary-0.8.2.0 bytestring-0.10.7.0"
```

What does this error mean?
How can I make things work?

**Comment by fizruk** [comment]
When specifying packages explicitely:

```yaml
compiler: ghc-8.0.0.20160204

setup-info:
  ghc:
    macosx:
      8.0.0.20160204:
        url: "http://downloads.haskell.org/~ghc/8.0.1-rc2/ghc-8.0.0.20160204-x86_64-apple-darwin.tar.xz"

packages:
  - integer-gmp-1.0.0.1
  - base-4.9.0.0
  - base-orphans-0.5.1
  - array-0.5.1.0
  - deepseq-1.4.2.0
  - containers-0.5.7.1
  - stm-2.4.4.1
  - transformers-0.5.1.0
  - StateVar-1.1.0.3
  - semigroups-0.18.1
  - transformers-compat-0.5.1.4
  - bytestring-0.10.7.0
  - binary-0.8.2.0
  - text-1.2.2.0
  - hashable-1.2.4.0
  - void-0.7.1
  - contravariant-1.4
  - filepath-1.4.1.0
  - time-1.6
  - unix-2.7.2.0
  - directory-1.2.5.0
  - ghc-boot-8.0.0.20160204
  - pretty-1.1.3.2
  - template-haskell-2.11.0.0
  - tagged-0.8.3
  - distributive-0.5.0.2
  - comonad-5
  - bifunctors-5.2.1
  - semigroupoids-5.0.1
  - profunctors-5.2
  - prelude-extras-0.4.0.3
  - mtl-2.2.1
  - exceptions-0.8.2.1
```

I get a different error:

```
$ stack build
Caching build plan
Fetched package index.
Populated index cache.
The following package identifiers were not found in your indices: base-4.9.0.0, bytestring-0.10.7.0, deepseq-1.4.2.0, ghc-boot-8.0.0.20160204, integer-gmp-1.0.0.1, template-haskell-2.11.0.0, unix-2.7.2.0
```
