### ISSUE TITLE
stack build --nix drops me into a shell

### ISSUE THREAD

**Issue by zimbatm** [commercialhaskell/stack#1778]
Hi,

unfortunately it's not an open-source repo but I've got something weird going on an would like to describe it the best that I can:

I have a project with a stack.yml that looks like this:
```yaml
---                                                                  
packages:
- .
- location:
    git: git@github.com:foo/bar.git
    commit: 9fabc6170a09e7a7aff5acaa8caffac0a30b90ed
    extra-dep: true
extra-deps:
  - messagepack-0.5.1
  - cereal-0.5.1.0
resolver: lts-4.1
```

```
$ stack --version
Version 1.0.2 x86_64
$ stack build --nix
< sleeps for a bit, no output >
[zimbatm@xps13:~/code/my/projet]$ <dropped into that nix-shell look-alike>
[zimbatm@xps13:~/code/my/projet]$ exit
$
```

Then I tried running it with `strace -fF` and I got a bunch of exit(1) at the end but it terminated. So I tried running `cat | stack build --nix` and got a proper Haskell compilation output with a complaint that zlib.h is not found.

I suspect that the command that you are running detected an interactive input and behaves differently in that case.
