### ISSUE TITLE
Add an option to specify build plan download address.

### ISSUE THREAD

**Issue by TerrorJack** [commercialhaskell/stack#1794]
Currently, stack downloads stackage build plans from s3.amazonaws.com. Unfortunately, in many areas in China, this domain is blocked due to the Great Firewall (national network censoring system).

So I'm proposing that stack add an option to specify build plan download address. This allows us to set up a stackage mirror along existing hackage mirrors in China, and Chinese Haskellers won't have to endure Internet connection issues in their workflow. Thank you!

**Comment by mgsloan** [comment]
Yeah, this would be good. Looks like the following URLs contain `amazonaws.com`:

![2016-02-17-200800_983x54_scrot](https://cloud.githubusercontent.com/assets/22570/13133668/4950f0e2-d5b2-11e5-92c6-d3f93f4c8e21.png)

So I suppose the solution here would be to allow configuration of something other than `https://s3.amazonaws.com`.  Something like `metadata-mirror: ...` in yaml configuration.

Is github also affected?  We also download things from github.

**Comment by TerrorJack** [comment]
Yes, github is also affected.

**Comment by mgsloan** [comment]
I see.  I suppose we could have something like:

```yaml
stack-urls:
    snapshots: https://s3.amazonaws.com/haddock.stackage.org/snapshots.json
    index: https://s3.amazonaws.com/hackage.fpcomplete.com/00-index.tar.gz"
    # etc
```

Alternatively, we could make it so that you can download some set of files and use those locally (see also https://github.com/commercialhaskell/stack/issues/1594 ).
