### ISSUE TITLE
Cannot install GHCJS while in Nix-shell mode

### ISSUE THREAD

**Issue by Rizary** [commercialhaskell/stack#1882]
Hi, I have the following stack.yaml:

```
# For more information, see: http://docs.haskellstack.org/en/stable/yaml_configuration.html

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-5.5

# Local packages, usually specified by relative directory name
packages:
- '.'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- ghcjs-dom-0.2.3.1
- ref-tf-0.4
- webkitgtk3-0.14.1.1
- webkitgtk3-javascriptcore-0.13.1.1
- haskell-src-exts-1.16.0.1
- syb-0.5.1
- aeson-0.9.0.1

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 1.0.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor

# add GHCJS configuration
compiler: ghcjs-0.2.0.20151230.3_ghc-7.10.2
compiler-check: match-exact
setup-info:
 ghcjs:
  source:
   ghcjs-0.2.0.20151230.3_ghc-7.10.2:
    url: "https://github.com/nrolland/ghcjs/releases/download/v.0.2.0.20151230.3/ghcjs-0.2.0.20151230.3.tar.gz"

#nix-configuration
nix:
 enable: true
 shell-file: ../../haskell-nix/shell.nix

```

and when i do 

` stack setup`

inside nix-shell mode, i got the following error:

```
Preparing to install GHCJS to an isolated location.
This will not interfere with any system-level installation.
No sha1 found in metadata, download hash won't be checked. 
Already downloaded.                                        
Unpacking GHCJS into /home/user/.stack/programs/x86_64-linux/ghcjs-0.2.0.20151230.3_ghc-7.10.2/src/ ...Expected a single directory within unpacked /home/user/.stack/programs/x86_64-linux/ghcjs-0.2.0.20151230.3_ghc-7.10.2.tar.gz

```

I have install stack inside the nix-shell, and when i do stack install (e.g. reflex-dom),:

`stack install reflex-dom`

 i got the following error:

```
No compiler found, expected exact version ghcjs-0.2.0.20151230.3_ghc-7.10.2 (x86_64) (based on resolver setting in /home/user/folrdertest/testinstall/stack.yaml).
Try running "stack setup" to install the correct GHC into /home/user/.stack/programs/x86_64-linux/

```

when doing stack setup, the same error above happened.

Any idea where i am doing wrong??
