### ISSUE TITLE
Build plans carry stale flags from previous package versions when package flags change

### ISSUE THREAD

**Issue by DanBurton** [commercialhaskell/stack#1927]
Stack init is pulling `text` into the `extra-deps` of the build plan, even though the same version is available via the specified snapshot. (Note that lts-5.8 has text-1.2.2.0). This causes project-local recompilation rather than reusing my snapshot's compiled packages for anything that transitively depends on `text`.

**To reproduce**

* `stack unpack strive-2.2.0 && cd strive-2.2.0`
* `stack init --resolver lts-5.8 --solver`

**Expected**

```
Extra-deps:
- gpolyline-0.1.0.1
```

**Actual**

```
extra-deps:
- gpolyline-0.1.0.1
- text-1.2.2.0
```

**Details**

```
stack --version
Version 1.0.4.2 x86_64
(mac)

cabal --version
cabal-install version 1.22.8.0
using version 1.22.7.0 of the Cabal library 
```

**Comment by harendra-kumar** [comment]
That looks like a bug. Let me take look.

**Comment by harendra-kumar** [comment]
Looks like there is something wrong with the lts-5.8 build plan. For the package text it says:

```
    constraints:                                                                                                                                                                  
      library-profiling: true                                                                                                                                                     
      flags:                                                                                                                                                                      
        integer-simple: false                                                                                                                                                     
      build-benchmarks: true                                                                                                                                                      
      skip-build: false                                                                                                                                                           
      tests: expect-success                                                                                                                                                       
      haddocks: expect-success                                                                                                                                                    
      version-range: ! '>=1.2.2.0 && <1.3'                                                                                                                                        
    version: '1.2.2.0'                 
```

Notice the `integer-simple` flag being set as false. But in `text-1.2.2.0` this flag was removed and `integer-pure` flag was added. From text.cabal in text-1.2.2.0:

```
flag developer
  description: operate in developer mode
  default: False
  manual: True

flag integer-pure
  description: Use the pure-Haskell integer library instead of GMP
  default: False
  manual: True
```

Why is the build plan using the old flag but new package version? The build plan seems to be screwed up. 

`stack init` is adding the text package in extra-deps due to the mismatch in the flags in the build plan and the package flags that the cabal-solver returned. Since flags are not the same we add it in the extra-deps.
