### ISSUE TITLE
No cabal file found using multi-package wxhaskell git repo

### ISSUE THREAD

**Issue by codygman** [commercialhaskell/stack#1973]
I'm attempting to use the latest version of [wxHaskell](https://github.com/wxHaskell/wxHaskell) in one of my projects. Here is my stack.yaml:

```yaml
flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:wxHaskell/wxHaskell.git
    commit: a833aca068de7cbfcb84490cf13bb7ff9089bbfc
extra-deps: []
resolver: lts-5.2
```

I get this error when I run `stack build`:

```
wx-hs-example λ stack build 
No .cabal file found in directory /home/cody/programming/haskell/hsqml-exp/wx-hs-example/.stack-work/downloaded/468996f554d05950590407398befd10c82d9a5e0d1687302355cfecbd04e34cb/
```

I'm guessing I'm missing something in my stack.yaml, but I couldn't find anything specific in the FAQ about multi-package git repos and how to make them work.

**Comment by harendra-kumar** [comment]
The error message is correct. Indeed, there is no .cabal file in the top level directory of wxHaskell repository. stack needs a cabal file to build. If you know which directories from this repository you want to build then you can use the `subdirs` key to specify those directories. More details about the usage can be found here:

https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md#packages

**Comment by codygman** [comment]
@harendra-kumar Thanks! The `subdirs` key is what I was looking for. My end result after your advice is:

```yaml
flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:wxHaskell/wxHaskell.git
    commit: a833aca068de7cbfcb84490cf13bb7ff9089bbfc
  subdirs: 
  - wx
  - wxc
  - wxcore
  - wxdirect
extra-deps: []
resolver: lts-5.2
```

**Comment by harendra-kumar** [comment]
Append a `extra-dep: true` as well.

```yaml
- location:
    git: git@github.com:wxHaskell/wxHaskell.git
    commit: a833aca068de7cbfcb84490cf13bb7ff9089bbfc
  subdirs: 
  - wx
  - wxc
  - wxcore
  - wxdirect
  extra-dep: true
```
