### ISSUE TITLE
stack build: Issues with flags

### ISSUE THREAD

**Issue by harendra-kumar** [commercialhaskell/stack#1995]
I wasted precious minutes trying to debug what's wrong when I made a mistake in defining and using a flag. The mistake I made was to put a ':' in the flag stanza of the cabal file, like this:

 `flag native:`

When I ran stack `build --flag unicode-transforms:native` it just said:

`These flags are used without having been defined: native`

This is likely to be a cabal issue. 

But what's strange is that with this mistake stack allows me to put any random name as a package name in stack.yaml flags section and on the command line flag spec without noticing anything wrong. E.g.

```
cueball:/vol/hosts/cueball/workspace/projects/unicode-transforms$ cat stack.yaml
flags:
    hahaha:
        native: true

extra-package-dbs: []
packages:
- '.'
extra-deps:
- data-list-sequences-0.1
resolver: lts-5.8

cueball:/vol/hosts/cueball/workspace/projects/unicode-transforms$ stack build --flag xxx:native 
These flags are used without having been defined: native
```
