### ISSUE TITLE
Error parsing targets: The specified targets matched no packages

### ISSUE THREAD

**Issue by yamafaktory** [commercialhaskell/stack#2018]
Hi,

After having successfully installed the compiler: ghcjs-0.2.0.20160409_ghc-7.10.2 from http://ghcjs.luite.com/, runned stack setup, then I get `Error parsing targets: The specified targets matched no packages` when trying to stack build.

**Steps to reproduce:**

```sh
stack new ghcjs
```

Edit the stack.yml file:

```yml
resolver: lts-5.11

packages:
- location:
    git: https://github.com/ryantrinkle/reflex.git
    commit: d5e5518d228ae895f6a83b17dc0ae794d4b9eec5
  extra-dep: true
- location:
    git: https://github.com/ryantrinkle/reflex-dom.git
    commit: eb61be8a2c7372df6b243bed7c37fbdb4d04938a
  extra-dep: true

extra-deps:
- ghcjs-dom-0.2.3.1
- ref-tf-0.4

flags: {}

extra-package-dbs: []

compiler: ghcjs-0.2.0.20160409_ghc-7.10.2
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160409_ghc-7.10.2:
        url: "http://ghcjs.luite.com/master-20160409.tar.gz"
```

```sh
stack setup
```

**Expected:**

Being able to run `stack build`.

**Actual**

```sh
Error parsing targets: The specified targets matched no packages
```

The weird thing is that I can run `stack ghci`

```sh
GHCJSi, version 0.2.0-7.10.2: http://www.github.com/ghcjs/ghcjs/  :? for help
Ok, modules loaded: none.
Prelude> 
```

My stack version is `Version 1.0.4.2 x86_64`
