### ISSUE TITLE
Force commit hashes in stack.yaml to be parsed as strings (and not numbers)

### ISSUE THREAD

**Issue by mitchellwrosen** [commercialhaskell/stack#2088]
stack.yaml:

```
resolver: lts-5.14
packages:
  - .
  - location:
      git: git@github.com:well-typed/binary-serialise-cbor.git
      commit: 3026281
    extra-dep: true
```

Result from `stack build`:

```
AesonException "failed to parse field 'packages': failed to parse field 'location': failed to parse field 'hg': key \"hg\" not present"
```

Eh? Do I have the syntax wrong, here?

(`Version 1.0.4.3 x86_64`)
