### ISSUE TITLE
GHC-Options flags being ignored in newer Stack builds

### ISSUE THREAD

**Issue by AaronFriel** [commercialhaskell/stack#2289]
Arch Linux and other rolling distro users are experiencing errors due to the assembler using an unhandled relocation type.

See: 
https://github.com/DanielG/ghc-mod/issues/762
https://github.com/gibiansky/IHaskell/issues/636

One trend with these reports is that some users report success from putting in their `config.yaml` or `stack.yaml` the lines:

```
ghc-options:
  cryptonite: -opta-Wa,-mrelax-relocations=no
```

Or variations thereof (e.g.: `"*": ...`).

I'm experiencing this as well, even when I try to ghc-options all the things:

```
rebuild-ghc-options: true
apply-ghc-options: everything
ghc-options:
  cryptonite: -opta-Wa,-mrelax-relocations=no
  cipher-aes: -opta-Wa,-mrelax-relocations=no
  "*": -opta-Wa,-mrelax-relocations=no
```

Even when I do that, `stack build cipher-aes` won't rebuild unless I use ghc-pkg to remove it (what?!) and even when I do, I still get these errors when using ghc-mod:

```
ghc-mod: /home/developer/.stack/snapshots/x86_64-linux/lts-6.4/7.10.3/lib/x86_64-linux-ghc-7.10.3/cipher-aes-0.2.11-LCbQiUgBdfG1swKGFESvIB/libHScipher-aes-0.2.11-LCbQiUgBdfG1swKGFESvIB.a: unhandled ELF relocation(RelA) type 42
```

An interesting observation is that *some users* report that the ghc-options command worked for them, specifically, @shimuuar noted:

> stack-1.0.4.3, no ghc-options: unhandled ELF relocation
> stack-1.0.4.3 cryptonite: -opta-Wa,-mrelax-relocations=no: works
> stack-1.1.2 with or without ghc-options: unhandled ELF relocation

Since it looks like a GHC version that fixes this won't be released soon, I'm wondering if it might be possible to see why Stack 1.1.2 is not working with these options?
