### ISSUE TITLE
Ignoring STACK_YAML custom config

### ISSUE THREAD

**Issue by Pitometsu** [commercialhaskell/stack#2335]
```
 $ STACK_YAML=stack_netsu.yaml stack clean                                         
Getting project config file from STACK_YAML environment
Run from outside a project, using implicit global project config
Using latest snapshot resolver: lts-6.6
```

When

```
 $ grep resolver: stack_netsu.yaml 
resolver: lts-6.5
```

**Comment by sjakobi** [comment]
I'm having difficulties reproducing this.

What's your `stack --version`?

Can you post the full `stack_netsu.yaml`?

**Comment by Pitometsu** [comment]
```
 $ stack --version
Version 1.1.2 x86_64 hpack-0.14.1
```
***
```
resolver: lts-6.5
- '.'
- location:
    git: https://github.com/snapframework/heist.git
    commit: 3ec7c1ea9187f3c7aa1ea0b9af86999c43781ca8
  extra-dep: true
- location:
    git: https://github.com/snapframework/io-streams-haproxy.git
    commit: 10aa31692920ccb73adf27ca73b00ca37c1c6acb
  extra-dep: true
- location:
    git: https://github.com/snapframework/snap-server.git
    commit: 7a5c389046e071bafe7d196378c678ced0ab985f
  extra-dep: true
- location:
    git: https://github.com/snapframework/snap-core.git
    commit: 55c055f9e6b8b7c884247ffa7df382c2759b966e
  extra-dep: true
- location:
    git: https://github.com/snapframework/snap.git
    commit: bbe0b65cc380ccd1b189d611b9220e4680d787de
  extra-dep: true
- location:
    git: https://github.com/snapframework/snap-loader-static.git
    commit: 75e8d0a8d725332098ea779a6e2995cc7b8e31fb  
  extra-dep: true
- location:
    git: https://github.com/snapframework/snap-loader-dynamic
    commit: 80f74a8bcf3e089c8c5b8a7a7a13298f7f4a2c71  
  extra-dep: true
- location:
    git: https://github.com/haskell-servant/servant.git
    commit: c2c9bef5715bdfb1819f54e00127a62f2fdc44ec
  subdirs:
  - servant
  - servant-blaze
  extra-dep: true
( . . . )
- location:
    git: https://github.com/dbp/hspec-snap.git
    commit: a09c22cd49affbd883236ffb13643642869c6863
  extra-dep: true
extra-deps:
   - listsafe-0.1.0.1
   - heist-1.0.0.0
   - hspec-snap-1.0.0.0
   - servant-0.6.1
   - servant-blaze-0.6.1
   - snap-1.0.0.0
   - snap-core-1.0.0.0
   - snap-server-1.0.0.0
   - ipprint-0.6
   - sr-extra-1.46.3.2
flags: {}
extra-package-dbs: []
docker:
  enable: true
  image: some-stack-based-image
  stack-exe: image
  mount:
    # hardcoded because of https://github.com/commercialhaskell/stack/issues/2324
    - "/home/netsu/.ghc/ghci.conf:/home/netsu/myproject/.stack-work/docker/_home/.ghc/ghci.conf"
```
