### ISSUE TITLE
How to test `stack image container`?

### ISSUE THREAD

**Issue by seanhess** [commercialhaskell/stack#2337]
I am very excited about `stack image container`. None of the tutorials mention how to test it locally. I'm running on a mac, and think I have everything set up correctly. I have an application created using `stack new` that creates a web server on port 8003, with the following stack.yaml:

```
resolver: nightly-2016-06-12

packages:
- '.'
extra-deps:
  - wai-cors-0.2.5

flags: {}

extra-package-dbs: []

image:
  container:
    name: my-app
    base: fpco/stack-run
    add:
      static: /app/static
```

It works with `stack exec` or via `stack ghci` just fine, and I can build the docker image:

```
$ stack image container
Sending build context to Docker daemon 37.94 MB
Step 1 : FROM fpco/stack-run
 ---> 4058365c474a
Step 2 : ADD ./ /
 ---> Using cache
 ---> cd02ac88a840
Successfully built cd02ac88a840
````

When I try to run the created docker container it seems to start up, but I can't find the server. 

```
$ docker run -it my-app
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 9
*** Running sudo -EHu root PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /usr/bin/env -- bash...
root@ea0f1391f296:/# Jul  5 23:26:55 ea0f1391f296 syslog-ng[17]: syslog-ng starting up; version='3.5.6'
```

So if I visit `localhost:8003` it can't find it. I'm using the new docker for osx, so it's not the vm. (For example, I can run nginx with the same command and hit it locally)

I've attached to the container and can see the static files, and the exe is in `/usr/local/bin/server-exe`, but it doesn't run. Is it because I am compiling from a mac? I thought `stack image container` was meant to address that?

How can I get this working, and how can I help improve the documentation?
