### ISSUE TITLE
"Stack status" command

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#2393]
It would be convenient to have a `stack status` command to query the current state of the project.  I'm imagining something like:

For `stack status --flag stack:disable-git-info`

```
stack-yaml: /home/mgsloan/fpco/stack/stack.yaml
local-packages:
  - stack:
      build-status: dirty
      enabled-flags:
        - disable-git-info: "Disable compile-time inclusion of current git info in stack"
      disabled-flags:
        - integration-tests: "Run the integration test suite"
        - static: "Pass -static/-pthread to ghc when linking the stack binary."      
      components:
        - "lib":
            build-status: dirty
            dirty-files:
              - src/Stack/Build/Execute.hs
        - "exe:stack":
            build-status: dirty
            dirty-files:
              - src/main/Main.hs
        - "test-suite:stack-test":
            build-status: unbuilt
        - "test-suite:stack-integration-test":
            build-status: unbuilt
            buildable: False
unbuilt-dependencies:
  - monad-control-1.0.1.0
  - monad-unlift-0.2.0

#2 unbuilt dependencies: monad-control, monad-unlift
# Use the "--all" flag to get more details that usually aren't needed.
```

This is a similar idea as `stack query`, and perhaps should be subsumed / merge.  The main difference is that this would load the build plan, etc, and provide a bunch of info.

Ideally this would be written in such a way that it's also efficient to output this info in verbose mode, before the build starts.
