### ISSUE TITLE
Blank error when running haddock for GHCJS-compiled project

### ISSUE THREAD

**Issue by eamsden** [commercialhaskell/stack#2395]
`$ stack haddock` fails with:

```
Running Haddock for ghcjs-base-0.2.0.0...
setup-Simple-Cabal-1.22.8.0-ghcjs-0.2.0_ghc-7.10.2:
'/home/eamsden/.stack/programs/x86_64-linux/ghcjs-0.2.0.20160718_ghc-7.10.2/bin/haddock-ghcjs'
exited with an error:
```

This is for a project depending on ghcjs-base with the following stack.yaml

```
# This file was automatically generated by 'stack init'
# 
# Some commonly used options have been documented as comments in this file.
# For advanced use and comprehensive documentation of the format, please see:
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# Resolver to choose a 'specific' stackage snapshot or a compiler version.
# A snapshot resolver dictates the compiler version and the set of packages
# to be used for project dependencies. For example:
# 
# resolver: lts-3.5
# resolver: nightly-2015-09-21
# resolver: ghc-7.10.2
# resolver: ghcjs-0.1.0_ghc-7.10.2
# resolver:
#  name: custom-snapshot
#  location: "./custom-snapshot.yaml"
resolver: lts-6.7

# User packages to be built.
# Various formats can be used as shown in the example below.
# 
# packages:
# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
# - location:
#    git: https://github.com/commercialhaskell/stack.git
#    commit: e7b331f14bcffb8367cd58fbfc8b40ec7642100a
# - location: https://github.com/commercialhaskell/stack/commit/e7b331f14bcffb8367cd58fbfc8b40ec7642100a
#   extra-dep: true
#  subdirs:
#  - auto-update
#  - wai
# 
# A package marked 'extra-dep: true' will only be built if demanded by a
# non-dependency (i.e. a user package), and its test suites and benchmarks
# will not be run. This is useful for tweaking upstream packages.
packages:
- '.'
- location:
    git: git@github.com:ghcjs/ghcjs-vdom.git
    commit: 1c1175ba22eca6d7efa96f42a72290ade193c148
- location:
    git: git@github.com:ghcjs/ghcjs-base.git
    commit: 552da6d30fd25857a2ee8eb995d01fd4ae606d22
- location:
    git: git@github.com:ghcjs/ghcjs-ffiqq.git
    commit: b52338c2dcd3b0707bc8aff2e171411614d4aedb
# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps: [ reactive-banana-1.1.0.1
            , pqueue-1.3.1.1]

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true
# 
# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=1.1"
# 
# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
# 
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
# 
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
compiler: ghcjs-0.2.0.20160718_ghc-7.10.2
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160718_ghc-7.10.2:
        url: https://s3.amazonaws.com/ghcjs/ghcjs-0.2.0.20160718_ghc-7.10.2.tar.gz
        sha1: abfb07de889ea17885810131d5745ad6cfacb4e9
```

If `haddock-ghcjs` is reporting an error, then Stack should not obscure what that error is.

**Comment by mgsloan** [comment]
Curious, not sure what's going on there!  I don't think stack is obscuring the error.  I think it failed with an exit code and no output.

**Comment by tolysz** [comment]
Hi, Just the XMas investigation :)
Could you try https://docs.haskellstack.org/en/stable/ghcjs/
Any `lts-7.14`+ builds? I tried and they build haddock for `ghcjs-base` while boot.
Please give some sample full repo.

**Comment by SpencerPark** [comment]
Sorry to bump this old issue but it is what came up when looking for a solution to this problem and it may help others that find this. 

With the older versions of ghcjs the installed haddock version doesn't support the `--hyperlinked-source` flag which stack provides by default. The error is with unknown flag and for whatever reason that error message isn't reported.

I believe it was added in haddock `2.16.2` but when running `stack exec -- haddock-ghcjs --version` I got `2.16.1` with
```yaml
resolver: lts-6.30
compiler: ghcjs-0.2.0.9006030_ghc-7.10.3
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.9006030_ghc-7.10.3:
        url: http://ghcjs.tolysz.org/lts-6.30-9006030.tar.gz
        sha1: 2371e2ffe9e8781808b7a04313e6a0065b64ee51
```

###### Solution

Provide the `--no-haddock-hyperlink-source` when running `stack haddock` to avoid stack providing the unknown argument.
