### ISSUE TITLE
Stack fails with a confusing message if the build depends on a git repository and git isn't installed

### ISSUE THREAD

**Issue by MnM** [commercialhaskell/stack#2420]
This is the error I'm getting when trying to build a stack project that depends on a git repository, but the machine doesn't have the `git` executable installed:
```
[root@acae814b97e1 example]# stack build
/example/.stack-work/downloaded/1G-hyVYpwk2Z/: getDirectoryContents: does not exist (No such file or directory)
```

Here's the relevant part of my `stack.yaml`:
```
packages:
  - location:
      git: https://github.com/MnM/http-client-auth
      commit: 9d43a040b6d865c6069b3310bc098c5e8ad79b1c
resolver: lts-6.4
```

And the `stack` executable I'm using:
```
[root@acae814b97e1 example]# stack --version
Version 1.1.2, Git revision cebe10e845fed4420b6224d97dcabf20477bbd4b x86_64 hpack-0.14.0
```
