### ISSUE TITLE
Failing to build ghcjs -- can't find 'bin-package-db'

### ISSUE THREAD

**Issue by lierdakil** [commercialhaskell/stack#2522]
### General summary/comments (optional)

Can't build ghcjs-0.2.0.20160414_ghc-7.10.3 (7.10.2 builds fine)

### Steps to reproduce

stack.yaml:

```yaml
resolver: lts-5.12
packages: ['.']
compiler: ghcjs-0.2.0.20160414_ghc-7.10.3
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160414_ghc-7.10.3:
        url: https://s3.amazonaws.com/ghcjs/ghcjs-0.2.0.20160414_ghc-7.10.3.tar.gz
        sha1: 6d6f307503be9e94e0c96ef1308c7cf224d06be3
```

1. Run command `stack setup`.

### Expected

GHCJS is installed.

### Actual

```
Preparing to install GHCJS to an isolated location.
This will not interfere with any system-level installation.
Downloaded ghcjs-0.2.0.20160414_ghc-7.10.3.               
Setting up GHCJS build environmentDownloaded lts-5.1Installing GHCJS (this will take a long time) ...Didn't see bin-package-db-0.0.0.0 in your package indices.
Updating and trying again.
Fetching package index ...remote: Counting objects: 1, done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.                    Fetched package index.    
The following package identifiers were not found in your indices: bin-package-db-0.0.0.0
```

`stack setup --verbose` output::

https://gist.github.com/lierdakil/318db3b0c6800c1f8f36c84850694aa6

### Stack version

```
$ stack --version
Version 1.1.2 x86_64 hpack-0.14.1
```

### Method of installation

Gentoo ebuild

Note: the same happens with stack downloaded from stackage.org:
```
Version 1.1.2, Git revision cebe10e845fed4420b6224d97dcabf20477bbd4b (3646 commits) x86_64 hpack-0.14.0
```

**Comment by rubenmoor** [comment]
Same here with same stack.yaml and stack version 1.1.3.

**Comment by themoritz** [comment]
Same problem here when using ghcjs and including `bin-package-db` as a dependency. So this in particular means that I can't compile ghcjs because it depends on `bin-package-db`.

stack.yaml:

```yaml
resolver: lts-5.16
compiler: ghcjs-0.2.0.20160628_ghc-7.10.3
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160628_ghc-7.10.3:
        url: https://s3.amazonaws.com/ghcjs/ghcjs-0.2.0.20160628_ghc-7.10.3.tar.gz
```

.cabal file:
```cabal
executable test
  main-is:             Main.hs
  build-depends:       base
                     , bin-package-db
  hs-source-dirs:      src
  ghcjs-options:       -Wall
  default-language:    Haskell2010
```

`bin-package-db` seems to be in the stackage snapshot: https://www.stackage.org/lts-5.16/package/bin-package-db-0.0.0.0

**Comment by schell** [comment]
I'm running into this with 
```
stack --version
Version 1.1.2 x86_64 hpack-0.14.0
```
and stack.yaml
```
compiler: ghcjs-0.2.0.20160907_ghc-7.10.3
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160907_ghc-7.10.3:
        url: http://ghcjs.luite.com/master-20160907.tar.gz

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-6.15

packages:
- '.'
- location:
    git: https://github.com/schell/gelatin.git
    commit: 2e1475ebab37f53961c33416924b7adfbf560496
  subdirs:
  - gelatin
  - gelatin-gl
  - gelatin-sdl2
  - gelatin-freetype2
- location:
    git: https://github.com/schell/renderable.git
    commit: fda35ce6d0f02f3e29bf8168305f8ac5421f40fd
- location:
    git: https://github.com/schell/htiled.git
    commit: b008faec3971d7088e4570abc42f94b0b510dde3
- location:
    git: https://github.com/schell/varying.git
    commit: cd1fc3ab5befb59f7b7d5940e5ee8da43ed54dd4
- location:
    git: https://github.com/schell/sdl2.git
    commit: aff05d74b6a11969c880ab410193ff44ec0905ee

- location:
    git: https://github.com/schell/shapes.git
    commit: 0f8a187695e9cd1228e79bb8a51f5a6a6de3469e
  subdirs:
  - shapes
  - shapes-math

extra-deps:
- FontyFruity-0.5.3.2
- halive-0.1.0.7
- freetype2-0.1.1
```
I've downloaded and built ghcjs using this stack.yaml and `stack setup`
