### ISSUE TITLE
 Strange stack.yaml behavior: extra-deps, aeson and GHCJS

### ISSUE THREAD

**Issue by mchaver** [commercialhaskell/stack#2556]
(Moved this over from [ghcjs github issues](https://github.com/ghcjs/ghcjs/issues/512) because I thought it was more appropriate here)

If you want to compile with ghcjs and stack, you can put declare the compiler in `stack.yaml`

```yaml
compiler: ghcjs-0.2.0.20160414_ghc-7.10.3
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160414_ghc-7.10.3:
        url: https://s3.amazonaws.com/ghcjs/ghcjs-0.2.0.20160414_ghc-7.10.3.tar.gz
        sha1: 6d6f307503be9e94e0c96ef1308c7cf224d06be3
```

This works pretty well. However, ~~once you add anything~~ if you add certain packages to `extra-deps` like `aeson-0.8.0.2` (see my comment below), stack will complain that it is missing `ghcjs-base`, and most likely `ghcjs-prim` as well, depending on what you import.

```
While constructing the BuildPlan the following exceptions were encountered:

--  While attempting to add dependency,
    Could not find package ghcjs-base in known packages

--  Failure when adding dependencies:    
      ghcjs-base: needed (-any), stack configuration has no specified version
```

So you have to manually add these packages:

```yaml

- location:
    git: git@github.com:ghcjs/ghcjs-base.git
    commit: 552da6d30fd25857a2ee8eb995d01fd4ae606d22
  extra-dep: true
- location:
    git: git@github.com:ghcjs/ghcjs.git
    commit: ce7b5736b53eb34ef5b913efdc560c7dafaf0b79
  extra-dep: true
  subdirs:
  - lib/ghcjs-prim
```

However, the commits I have here don't seem to match up with the compiler version because once I add `ghcjs-base` and `ghcjs-prim` as extra-deps and use `toJSVal` in some code, I get:

```
uncaught exception in Haskell main thread: h$ap_1_0_fast: unexpected closure type: -1
```

If I remove the `extra-deps`, `ghcjs-base` and `ghcjs-prim`, that error goes away, but I am prevented from using packages outside of the stack declaration.

Run into the same issue if you do `stack --compiler ghcjs-0.2.0.20160414_ghc-7.10.3` and have extra-deps.

Related issue:
https://github.com/commercialhaskell/stack/issues/2436
