### ISSUE TITLE
Travis GHCJS build fails when using LTS 6.16

### ISSUE THREAD

**Issue by geraldus** [commercialhaskell/stack#2607]
I tried to use recent version of **LTS 6** snapshot series for one of my packages.  I switched from **LTS 6.6** to **LTS 6.16**, after that GHCJS build fails with following error:

```
random-1.1: using precompiled package
Running /home/travis/.stack/programs/x86_64-linux/ghcjs-0.2.0.20160917_ghc-7.10.3/bin/ghcjs-pkg --user --no-user-package-db --package-db /home/travis/.stack/snapshots/x86_64-linux/lts-6.18/ghcjs-0.2.0_ghc-7.10.2/pkgdb describe --simple-output random --expand-pkgroot exited with ExitFailure 1
ghcjs-pkg-0.2.0-7.10.2: cannot find package random
```
### Example Logs

[LTS 6.18 fail](https://travis-ci.org/agocorona/transient-universe/jobs/160820202)
[LTS 6.6 OK](https://travis-ci.org/agocorona/transient-universe/jobs/160821907)

I've tried **LTS 6.18** and it results in error too (I didn't try versions 6.7 – 6.15 though).  I also tried two different versions of GHCJS compiler: `ghcjs-0.2.0.20160703_ghc-7.10.3` and `ghcjs-0.2.0.20160917_ghc-7.10.3`.  Also I tried to upgrade built-in **NodeJS** (from `0.10.36` to `6.6.0` via `nvm intall 6`):

Example `stack-ghcjs.yaml` for GHCJS build:

```
resolver: lts-6.6
packages:
- '.'
- location:
    git: https://github.com/agocorona/transient.git
    commit: b06645a46462e68a2712de8ecd0d8f325b07a520
  extra-dep: true
extra-package-dbs: []
flags: {}

compiler: ghcjs-0.2.0.20160917_ghc-7.10.3
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160917_ghc-7.10.3:
         url: http://ghcjs.luite.com/master-20160917.tar.gz
```

I used example Travis script from Stack's docs, so `stack` is installed via

```
curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
```

GHCJS installations:

``` bash
# $ARGS = --stack-yaml=stack-ghcjs.yaml
# before install
stack --no-terminal setup $ARGS
stack --no-terminal --install-ghc $ARGS test --only-dependencies

# package build
stack --no-terminal $ARGS test --haddock --no-haddock-deps
```
