### ISSUE TITLE
Have setup-info support specification of a ghc build directory

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#2633]
I haven't put a great deal of thought into this idea, but it seems like it's a good feature for those developing on GHC while using stack.  The idea is to allow pointing at the root of a GHC source tree, or its `inplace` dir, and running it directly out of there.

So, in your global `config.yaml`, you could have something like the following:

```
ghc:
    linux64:
        8.0
            version: 8.0.2
            ghc-source-path: "/home/mgsloan/oss/haskell/ghc"
```

And it would magically use your development version of GHC!

I hope to be returning to iterating on my in-flight ghc patch soon, so that will be a good excuse to revisit this.

**Comment by simonmar** [comment]
I don't understand why you need a special feature for this.  Why wouldn't it work to just tell Stack to use `~/ghc/inplace/bin/ghc-stage2`? This is what we do with Cabal & cabal-install. (there's a bit of special magic I believe to find the relevant `ghc-pkg` program, but it's not hard)

**Comment by mgsloan** [comment]
Good point @simonmar, thanks for commenting !  It is because I am not yet familiar with GHC development workflows.

With that considered, this would look like:

```
ghc:
    linux64:
        8.0
            version: 8.0.2
            bin-path: /home/mgsloan/oss/haskell/ghc/inplace/bin/ghc-stage2
```
