### ISSUE TITLE
setup-info.ghcjs.source.*.url can't be relative

### ISSUE THREAD

**Issue by alexanderkjeldaas** [commercialhaskell/stack#2738]
Please use the following schema for your bug report:
### General summary/comments (optional)

The inability to use relative paths for the source of a compiler is hindering important use-cases.
### Steps to reproduce
1. Try using stackage nightly with ghcjs.
2. Understand that you need to use ghcjs-stack
3. Clone this repo into your "megarepo" (single repo)
4. Make it build ghcjs for stackage nightly.
5. Point your `stack.yaml` file to the artifact.
6. Now see `stack` complain.
7. Fail, no profit for you.

```
compiler: ghcjs-0.2.1.9007003_ghc-8.0.1
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007003_ghc-8.0.1:
          url: ../../third-party/ghcjs-stack/archive.tar.gz
```
### Expected

That it works.
### Actual

```
$ stack setup
Preparing to install GHCJS to an isolated location.
This will not interfere with any system-level installation.
user error (`url` must be either an HTTP URL or absolute file path: ../../third-party/ghcjs-stack/archive.tar.gz)
```
### Stack version

```
$ stack --version
Version 1.2.1, Git revision e3d9d35ad10129253541fb1cbe0b06c9aa73d7cb x86_64 hpack-0.14.1
```
### Method of installation
- Official binary, downloaded from stackage.org or fpcomplete's package repository
- Other (please specify)
  via `stack upgrade --git`
