### ISSUE TITLE
Stack w/ docker + compiler flag puts work in old project dir

### ISSUE THREAD

**Issue by shanemikel** [commercialhaskell/stack#2749]
I decided to play around with ghcjs, first using some example repo, but I couldn't get it to build.  So I rm the directory, and created my own stack project somewhere else.  I've been using this from the docs:

```
resolver: lts-6.21
compiler: ghcjs-0.2.0.9006021_ghc-7.10.3
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.9006021_ghc-7.10.3:
         url: http://ghcjs.tolysz.org/lts-6.21-9006021.tar.gz
         sha1: 80b83f85dcec182093418e843979f4cee092fa85
```

Anyway, stack keeps putting the build stuff in the old directory (creating the nonexistent one instead of using the current project dir).

BTW, I've been using docker for this (yes, via stack).. I've also tried `stack docker reset`

P.S.
Can somebody please update the fpco/stack-ghcjs images, because this take a real long time to build (or give me a hint about building it myself)
