### ISSUE TITLE
Stack reclones git packages too eagerly causing unnecessary compilation

### ISSUE THREAD

**Issue by parsonsmatt** [commercialhaskell/stack#2796]
### General summary/comments (optional)

The Problem:

I have a `stack.yaml` with some packages:

```yaml
packages:
  - foobar/
  - foobar-models/
  - location:
     git: git@github.com:qrilka/esqueleto
     commit: 607f6692f0539df4e4f0e1d14beffcc6df2cdc49
    extra-dep: true
```

`foobar-models` takes a really long time to compile, so it's split off into it's own package. Generally this is great! However, the `esqueleto` dependency gets confused, and reclones pretty regularly, causing a complete rebuild of `foobar-models` and `foobar`.

### Steps to reproduce

I don't have any public projects that I can reproduce this with, but I can attempt to get a minimal reproduction of a proprietary project if it would help.

### Expected

Git dependencies are only cloned/compiled once per change of the `stack.yaml` entry for them.

### Actual

Git dependencies are rebuilt regularly, causing multiple packages to be rebuilt.

### Stack version

```
$ stack --version
Version 1.2.1, Git revision b75ec0cf82c2e8d1cb6f1bf85cf0244ada55cc61 x86_64 hpack-0.14.1
```

### Method of installation

`stack upgrade --git`
