### ISSUE TITLE
Linker issues with stack setup building ghcjs

### ISSUE THREAD

**Issue by eamsden** [commercialhaskell/stack#2817]
### General summary/comments (optional)

Stack HEAD (as of 241cd07d576d9c0c0e712e83d947e3dd64541c42) builds ghc but not ghcjs on Ubuntu 16.10

### Steps to reproduce

    $ stack upgrade --git
    $ cd my-ghcjs-project
    $ stack setup

Relevant portion of stack.yaml

    resolver: lts-7.8
    compiler: ghcjs-0.2.1.9007008_ghc-8.0.1
    compiler-check: match-exact
    
    setup-info:
      ghcjs:
        source:
          ghcjs-0.2.1.9007008_ghc-8.0.1:
              url: http://ghcjs.tolysz.org/ghc-8.0-2016-11-07-lts-7.8-9007008.tar.gz
              sha1: 190300a3725cde44b2a08be9ef829f2077bf8825

### Expected

`$ stack setup` returns without errors, allowing me to proceed to `$ stack build`

### Actual

`$ stack setup`

then a slew of linker errors resembling

    /usr/bin/ld: /home/eamsden/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/rts/libCffi.a(ffi64.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC`

Appears very similar to #2712, except ghc-8.0.1 builds successfully and ghcjs fails with linker errors.

### Method of installation.

Other (please specify):

`stack upgrade --git`

**Comment by mgsloan** [comment]
I suspect indeed that this is the same as #2712, marking as blocked

**Comment by sigrlami** [comment]
Also, having link issue with network package and GHCJS. Setup:
```
compiler: ghcjs-0.2.1.820161126_ghc-8.0.1
compiler-check: match-exact  

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.820161126_ghc-8.0.1:
        url: http://tolysz.org/ghcjs/untested/ghc-8.0-2016-11-26-nightly-2016-11-26-820161126.tar.gz
        sha1: cf37fda561c043dc2f0ba31fae92c324cf1d0172

```
Error:
```
 Preprocessing library network-2.6.3.1...
    Types.hsc: In function ‘main’:
    Types.hsc:1080:5: warning: implicit declaration of function ‘hsc_alignment’ [-Wimplicit-function-declaration]
    Types.hsc:1080:20: error: expected expression before ‘struct’
...
```
