### ISSUE TITLE
stack build --file-watch detects changes in .git/index

### ISSUE THREAD

**Issue by lloucas-imvu** [commercialhaskell/stack#2821]
```
% stack build --file-watch
ExitSuccess
Type help for available commands. Press enter to force a rebuild.
ivan-0.1.0.0: unregistering (local file changes: .git/index)
```

### yaml
```
# For more information, see: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: nightly-2016-11-30

# Local packages, usually specified by relative directory name
packages:
- '.'
- externals/test-preproc/
- location:
    git: git@github.com:tebello-thejane/esqueleto.git
    commit: ea00e73e0496464500d4e35d1c9108b55fe186a5
  extra-dep: true
- location:
    git: git@github.com:Gabriel439/Haskell-Turtle-Library.git
    commit: 9762a7524468520c41a6ea7c581d93a20c91d0a3
  extra-dep: true

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- managed-1.0.5
- optional-args-1.0.1

# Override default flag values for local packages and extra-deps
flags:
  ivan:
    static: false
  test-preproc:
    static: false

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 0.1.4.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
```

### Expected

Id figure it wouldnt do a rebuild on .git/ file changes

### Stack version

```
% stack --version
Version 1.2.0, Git revision 241cd07d576d9c0c0e712e83d947e3dd64541c42 (4054 commits) x86_64 hpack-0.14.0
```
