### ISSUE TITLE
Poor performance when building many packages

### ISSUE THREAD

**Issue by tfausak** [commercialhaskell/stack#2831]
I was curious about the relative performance of lots of declarations vs. modules vs. packages. I wrote [a benchmark](https://gist.github.com/tfausak/dc8b6a05d3c4f55d8f6c50364de2d852/612598b0597bbe515489a3ac378e4de8a6d747c8) that creates a Stack project with some number of those things and times how long it takes to build. The raw results from 1 to 64 are available in [this Google doc](https://docs.google.com/a/fausak.me/spreadsheets/d/1PrquHZO2dO8ye-OEvUqeNOO_wpXYU5pCRFsExZK9GJU/edit?usp=sharing). Here they are graphed:

![](https://cloud.githubusercontent.com/assets/408753/20977946/afdbc50c-bc6c-11e6-91bf-eed69de59e01.png)

As you can see, adding declarations or modules does not significantly increase the build time. However, the build time is linearly correlated to the number of packages. I expected this to a certain extent because packages do a lot more than modules or declarations. I didn't expect each package to add 0.6 seconds to the build time, though. 

I know this isn't a problem per se, but it's unfortunate that building 10 packages incurs a 6 second performance penalty. I don't have any insight into why Stack takes that long. Is this worth exploring, or is this just the price that must be paid to compile a Haskell package?

---

For this benchmark the declarations, modules, and packages are as simple as possible. Here's what a module would look like:

``` hs
module P0m0 where
p0m0d0 :: ()
p0m0d0 = ()
```

And here's a package definition:

```
name: p0
version: 1.2.3
build-type: Simple
cabal-version: >= 1.10
library
  default-language: Haskell98
  build-depends: base
  exposed-modules:
    P0m0
```

And here's the Stack config:

``` yaml
resolver: lts-7.12
packages:
  - p0
```
