### ISSUE TITLE
Can't build unix package with Stack on CI

### ISSUE THREAD

**Issue by fizruk** [commercialhaskell/stack#2833]
I am trying to build a project that has `unix` as a transitive dependency. Unfortunately it fails with linker errors. I suspect that it has something to do with there being 2 versions of GHC installed:
- Circle CI has GHC 7.6 installed by default;
- I am installing GHC 8.0.2-rc1 using `stack setup`.

Here's an output of `stack build unix -v` on CI: https://gist.github.com/fizruk/5573c7ce6e6fddc39fc3e89e29ac9c64

Perhaps the essence of the error may be captured by this part:

```
    configure: WARNING: unrecognized options: --with-compiler
    Building unix-2.7.2.0...
    Preprocessing library unix-2.7.2.0...
    [ 1 of 39] Compiling System.Posix.User ( .stack-work/dist/x86_64-linux/Cabal-1.24.1.0/build/System/Posix/User.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.1.0/build/System/Posix/User.o )
    /tmp/ghc56715_0/ghc_19.o: In function `r9Su_closure':
    (.data+0x0): multiple definition of `__stginit_unixzm2zi7zi2zi0zm6lNTB03KKAWD3td2onXjYn_SystemziPosixziUser'
    /tmp/ghc56715_0/ghc_19.o:(.data+0x0): first defined here
    /tmp/ghc56715_0/ghc_19.o: In function `r9SG_closure':
```

Here's the relevant part of my `stack.yaml`:

```yaml
resolver: nightly-2016-12-07
compiler-check: match-exact
compiler: ghc-8.0.1.20161117
setup-info:
  ghc:
    linux64:
      8.0.1.20161117:
        url: http://downloads.haskell.org/~ghc/8.0.2-rc1/ghc-8.0.1.20161117-x86_64-deb8-linux.tar.xz
        content-length: 112047972
        sha1: 6a6e4c9c53c71cc84b6966a9f61948542fd2f15a
    macosx:
      8.0.1.20161117:
        url: https://downloads.haskell.org/~ghc/8.0.2-rc1/ghc-8.0.1.20161117-x86_64-apple-darwin.tar.xz
        content-length: 113379688
        sha1: 53ed03d986a49ea680c291540ce44ce469514d7c
image:
  container: ...
```

`image.container` part might be relevant because I believe it enables `--system-ghc`. And that might be a problem.

To reproduce this problem you can use this in your `circle.yml`:

```yaml
dependencies:
  override:
    - wget -q -O- http://download.fpcomplete.com/ubuntu/fpco.key | sudo apt-key add -
    - echo 'deb http://download.fpcomplete.com/ubuntu/precise stable main' | sudo tee /etc/apt/sources.list.d/fpco.list
    - sudo apt-get update
    - sudo apt-get install stack -y
    - stack --version
    - stack setup
    - stack build unix -v
```
