### ISSUE TITLE
Warnings aren't visible

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#298]
Currently there isn't any indication that a warning was outputted while building a package.  This can be resolved by grepping for `Warning:` in logs, but that's a bit hacky and you need to remember to do it.

I realize that it could be a bit problematic to extract out the warnings from the rest of GHC's output.  Instead of going for that level of support, it would be helpful to simply inform the user that there appear to be warnings (by searching for `Warning:` in the logs.  This might look like this:

```
foo-0.0.1: configure
foo-0.0.1: build
foo-0.0.1: warnings encountered - see /home/mgsloan/foo/.stack-work/logs/foo-0.0.1.log
foo-0.0.1: install
```

**Comment by chrisdone** [comment]
We discussed parsing GHC's and having a `Conduit ByteString m Message` kind of conduit that would have use in a number of applications. I don't think it'd be too problematic or unreasonable to print out any messages captured. Niklas also requested this.

**Comment by snoyberg** [comment]
I'm not opposed to this change, but given the way stack works now I think it's not terribly urgent. When working on a single package, all output is sent to the console, so you'll see the warnings. The only time when the warnings are hidden away in a log file is when you're building multiple packages at once, where (IME) not seeing the warnings is acceptable.

Another option to work around this is to use the `--pedantic` flag.

**Comment by alanz** [comment]
A note:

"When working on a single package, all output is sent to the console"

I just ran this against a single package with a warning, and it is silent, although there are warnings in the log file.

`--pedantic` shows the output, but then also enables `-Werror` which breaks the build.

    Version 0.1.0.0, Git revision 2354251bb06d761c8e63d6993c6971673a729d8a

**Comment by snoyberg** [comment]
I need a little more information about what's going on here. When I run `stack build` on a single project, I see all output generated by GHC stream to the console. Are you seeing that? If not, we should understand why that's not triggering here.

**Comment by alanz** [comment]
The project in question is https://github.com/alanz/ghc-exactprint/tree/wip at commit 27e90e45729f81b7a1b439ca2a04cc4d169d2d56

Using current ghc-7.10 head, and
stack Version 0.1.0.0, Git revision cbde66af9a2ff51233123f877983e85759b581bf

What I see after deleting `.stack-work` is

```
alanz@alanz-laptop:~/mysrc/github/alanz/ghc-exactprint$ rm -fr .stack-work
alanz@alanz-laptop:~/mysrc/github/alanz/ghc-exactprint$ stack build
refact-0.1.0.0: configure
ghc-syb-utils-0.2.3: configure
refact-0.1.0.0: build
ghc-syb-utils-0.2.3: build
refact-0.1.0.0: install
ghc-syb-utils-0.2.3: install
ghc-exactprint-0.3: configure
ghc-exactprint-0.3: build
ghc-exactprint-0.3: install
Completed all 3 actions.
```

However, the log file has

```
[ 9 of 10] Compiling Language.Haskell.GHC.ExactPrint.Transform ( src/Language/Haskell/GHC/ExactPrint/Transform.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Language/Haskell/GHC/ExactPrint/Transform.o )

src/Language/Haskell/GHC/ExactPrint/Transform.hs:153:5: Warning:
    Pattern match(es) are non-exhaustive
    In an equation for ‘go’: Patterns not matched: GetSortKey _ _
[10 of 10] Compiling Language.Haskell.GHC.ExactPrint ( src/Language/Haskell/GHC/ExactPrint.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Language/Haskell/GHC/ExactPrint.o )
```

Perhaps it is related to a git ref for a location?

**Comment by snoyberg** [comment]
Try running `stack build ghc-exactprint` instead. If that works for showing the output, I believe this will fix the problem correctly:

```yaml
flags: {}
packages:
- '.'
- location:
    git: git@github.com:mpickering/refact
    commit: 5fc6585cefb50a0fddba0f56cc8dabb9fad832e8
  valid-wanted: false
extra-deps:
  # - ghc-7.10.1.20150612
  - ghc-syb-utils-0.2.3
resolver: nightly-2015-06-16
# resolver: lts-2.14
```

The `valid-wanted` thing is a bad name, and is fixed on master to be `dependency`... anyway, give that a shot, if it works, you can switch to `dependency: true` when you upgrade stack next.

**Comment by alanz** [comment]
Using `stack build ghc-exactprint` does show the warnings.

Setting either `valid-wanted: false` or `dependency: true` made no difference to the bare `stack build` case (after upgrade to current master)

**Comment by snoyberg** [comment]
Sorry, I got the syntax incorrect, it's `extra-dep: true`. For me, I get the expected behavior with the following stack.yaml:

```
flags: {}
packages:
- '.'
- location:
    git: git@github.com:mpickering/refact
    commit: 5fc6585cefb50a0fddba0f56cc8dabb9fad832e8
  extra-dep: true
extra-deps:
  # - ghc-7.10.1.20150612
  - ghc-syb-utils-0.2.3
resolver: nightly-2015-06-16
# resolver: lts-2.14
```

```
$ stack --version
Version 0.1.0.0, Git revision 5b6794647eef2c87f9c1cfb12a0dd23ad541b656
```
