### ISSUE TITLE
Track packages that have flags to switch between integer-simple and integer-gmp

### ISSUE THREAD

**Issue by iand675** [commercialhaskell/stack#3031]
### General summary/comments (optional)

Perhaps more so than any other flag I've seen, many packages either have a flag `integer-gmp` which defaults to true or an `integer-simple` which defaults to false.

Since integer-gmp and integer-simple are mutually exclusive currently, it would be nice to automatically toggle these flags appropriately. Otherwise, one ends up with something like this in the stack.yaml file, which is just drudgery:

``` yaml
extra-deps:
- hashable-1.2.5.0
- text-1.2.2.1
- integer-logarithms-1.0.1
- cryptonite-0.22
- scientific-0.3.4.10

flags:
  hashable:
    integer-gmp: false
  text:
    integer-simple: true
  integer-logarithms:
    integer-gmp: false
  cryptonite:
    integer-gmp: false
  scientific:
    integer-simple: true
```
