### ISSUE TITLE
Stack unnecessarily rebuilds due to extra source files

### ISSUE THREAD

**Issue by NorfairKing** [commercialhaskell/stack#3065]
Please use the following schema for your bug report:

### Steps to reproduce

1. Find a package with a non-empty 'extra-sources' section in the cabal file.
`git@github.com:NorfairKing/quickspec.git` for example
2. Use it in your stack.yaml as follows:
```
- location:
      git: git@github.com:NorfairKing/quickspec.git
      commit: f5f73edc4807b925f36201c5791178171186619b
  extra-dep: true
```
3. `stack build`
4. `stack clean easyspec`
5. `stack build --pedantic --haddock --test quickspec:lib`

### Expected

No unnecessary rebuild

### Actual

```
quickspec-2: unregistering (local file changes: README.asciidoc examples/Arith.hs examples/Bools.hs examples/Combinators.hs examples/Composition....)
```

### Stack version

```
$ stack --version
Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd (4640 commits) x86_64 hpack-0.17.0
```

**Comment by mgsloan** [comment]
Can you please post the full stack.yaml config?

I get compilation errors in quickspec with

```
resolver: lts-8.5
packages:
  - .
  - location:
      git: git@github.com:NorfairKing/quickspec.git
      commit: f5f73edc4807b925f36201c5791178171186619b
    extra-dep: true
extra-deps:
- jukebox-0.2.17
- twee-0.1
- minisat-0.1.2
```

I'm also a bit confused by the following aspects of the repro:

1) Don't we expect a rebuild because a `stack clean` was run?

2) Is `--pedantic --haddock --test` actually necessary?

**Comment by NorfairKing** [comment]
Full stack config:

```
flags: {}
packages:
- './easyspec'
- location:
      git: git@github.com:NorfairKing/quickspec.git
      commit: f5f73edc4807b925f36201c5791178171186619b
  extra-dep: true
extra-deps:
- optparse-applicative-0.13.2.0
- validity-containers-0.1.0.2
- quickspec-0.9.6
- validity-0.3.2.0
- validity-path-0.1.0.0
- genvalidity-0.3.1.0
- genvalidity-hspec-0.3.1.0
- genvalidity-path-0.1.0.0
- jukebox-0.2.14
- twee-0.1
- minisat-0.1.2
resolver: lts-8.5
```

1. I don't expect rebuild of a dependency?
2. Yes. Even if it wasn't it should still be possible to run this without the dependency rebuilding.
My use case requires that the --pedantic does NOT apply to dependencies because dependencies are not as pedantic about code as I am.
