### ISSUE TITLE
GHC installation doesn't work from root folder

### ISSUE THREAD

**Issue by varosi** [commercialhaskell/stack#3188]
### Steps to reproduce

For example:

1. Put in the root of some drive (D:) ghc archive
2. Copy yaml file:

```
sevenzexe-info:
    url: "https://github.com/fpco/minghc/blob/master/bin/7z.exe?raw=true"
    content-length: 73728
    sha1: 187dff8a3327da87050f678579816e5bae40c632
sevenzdll-info:
    url: "https://github.com/fpco/minghc/blob/master/bin/7z.dll?raw=true"
    content-length: 447488
    sha1: 168a288d4456f0473f66e86a2d6fec4eb6f4b993
msys2:
    windows64:
        version: "20150512"
        url: "https://github.com/fpco/minghc/releases/download/2015-05-14/msys2-base-x86_64-20150512.tar.xz"
        content-length: 33451040
        sha1: 88fa66ac2a18715a542e0768b1af9b2f6e3680b2
ghc:
    windows64-integersimple:
        8.0.2:
            url: "D:/ghc-8.0.2-x86_64-unknown-mingw32-integer-simple.tar.xz"
```

3. Run 'stack setup --stack-setup-yaml stack-setup-2.yaml --reinstall --ghc-variant integersimple'

### Expected

To work as it is working if GHC archive is moved into a folder D:\ttt\

### Stack version

```
stack --version
Version 1.4.1, Git revision ea10057da1b1a49d937e7bcb6f997360bec1f863 (4765 commits) x86_64 hpack-0.17.0
```
