### ISSUE TITLE
Script interpreter support for git-backed packages

### ISSUE THREAD

**Issue by lexi-lambda** [commercialhaskell/stack#3218]
Currently, the `stack script` command supports specifying extra-deps from Hackage via the `--package` flag, but it does not provide any way to use packages from git. This would be a nice feature to have, since it seems fairly common that I would want to extract shared pieces of scripts into a separate repository, but I don’t necessarily have any reason to publish them to Hackage (since they’re quite specific to my use case).

I’m not sure what the right interface for this is, since at some point it just seems like it would be easier to provide a string in the stack.yaml format rather than duplicate all of its options, but it would also be possible to just add another flag.

**Comment by snoyberg** [comment]
The script command doesn't actually allow specifying extra-deps, in order to ensure reproducibility that functionality was specifically removed. The same would apply to Git repos. You could theoretically add this kind of support for the `runghc` approach (which does still support extra-deps), but I'd be skeptical that a good command line interface for this exists, and instead rely on a local `stack.yaml` file.

**Comment by snoyberg** [comment]
There's a better option for this now: using custom snapshots that specify Git repos. Can you give that approach a shot (using a build from master with extensible snapshot support)?

**Comment by tfausak** [comment]
I wasn't able to run a script with a custom snapshot. I tried a local snapshot and got this error:

```
Downloaded snapshot specified a 'resolver: { location: filepath }' 
field, but filepaths are not allowed in downloaded snapshots.
```

Then I tried a snapshot on the web and got a different error:

```
Would need to add some paths to the PATH environment variable to continue, but they would be invalid because they contain a ':'.
Please fix the following paths and try again:
/Users/fausata/.stack/script/custom: http:/lpaste.net/raw/1526350889311272960/.stack-work/install/x86_64-osx/custom-snapshot-BScKOT9lJ7Y3/8.0.2/bin/
```

I put everything into a project to make sure it worked that way. It did.

``` yaml
# snapshot.yaml
name: snapshot
resolver: ghc-8.0.2
packages:
  - git: https://github.com/tfausak/flow
    commit: 9656ba67fab8663f5adbbfdfda92a8dd9bbc3fb9
```

``` yaml
# stack.yaml
resolver: snapshot.yaml
```

``` yaml
# package.yaml
name: example
version: 0.0.0
executables:
  example:
    main: example.hs
    dependencies: [ base, flow ]
```

``` hs
-- stack --resolver snapshot.yaml script --package flow
-- This is example.hs but this comment can't go on the first line because Stack needs it.
-- Also tried with `--resolver http://lpaste.net/raw/1526350889311272960`.
import Flow
main = "Hello, world!" |> putStrLn
```
