### ISSUE TITLE
1.4.1 extra-deps git repo requires subdirs

### ISSUE THREAD

**Issue by tomsmalley** [commercialhaskell/stack#3262]
Version 1.4.1, Git revision 84114192b920a207cdcb12f5498fee2b83b2b85e x86_64 hpack-0.17.0

With the new extra-deps functionality, a stack.yaml file with:

```yaml
extra-deps:
- git: https://github.com/reflex-frp/reflex
  commit: 50305c797c41a27660b74f543e204e902c086bbf
- git: https://github.com/reflex-frp/reflex-dom
  commit: a20e829214e5330a2d829bcf156046b1fe24a169
  subdirs:
  - reflex-dom
  - reflex-dom-core
```

Gives an error like:

```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for reflex-dom-0.4:
    reflex must match ==0.5.*, but the stack configuration has no specified version
needed due to client-0.1.0.0 -> reflex-dom-0.4

Recommended action: try adding the following to your extra-deps in stack.yaml:
- reflex-0.4.0

You may also want to try the 'stack solver' command
Plan construction failed.
```

Restructuring the stack.yaml file allows the build to work:

```yaml
extra-deps:
- git: https://github.com/reflex-frp/reflex
  commit: 50305c797c41a27660b74f543e204e902c086bbf
  subdirs:
  - .
- git: https://github.com/reflex-frp/reflex-dom
  commit: a20e829214e5330a2d829bcf156046b1fe24a169
  subdirs:
  - reflex-dom
  - reflex-dom-core
```

I don't think this is intended behaviour since the packages section (with extra-dep: true) would not require this.

**Comment by eamsden** [comment]
This seems to also be the case in legacy stack.yaml files with a `packages` entry of the form
```
- location:
  git: git@github.com:eamsden/my-experimental-package.git
  commit: e62999f9ece7d9218b9768a908f8df9c11d7e920
  extra-dep: true
```
