### ISSUE TITLE
stack setup with ghcjs compiler fails

### ISSUE THREAD

**Issue by p-alik** [commercialhaskell/stack#3284]
I created a new project and followed the [instructions](https://docs.haskellstack.org/en/stable/ghcjs/) but unfortunately `stack setup` failed with exception:
```
Booting GHCJS (this will take a long time) ...Process exited with ExitFailure 1: /home/palik/.stack/programs/x86_64-linux/ghcjs-0.2.1.9007019_ghc-8.0.1/src/.stack-work/install/x86_64-linux/lts-7.19/8.0.1/bin/ghcjs-boot --clean
```

https://github.com/commercialhaskell/stack/blob/master/doc/ghcjs.md

### Steps to reproduce

- create new project

```
$ stack new test --resolver  lts-7.19
```
- add compiler and setup-info instractions from the [example-configurations](https://github.com/commercialhaskell/stack/blob/master/doc/ghcjs.md#example-configurations) to `stack.yaml` 
```
resolver: lts-7.19
compiler: ghcjs-0.2.1.9007019_ghc-8.0.1
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007019_ghc-8.0.1:
           url: http://ghcjs.tolysz.org/ghc-8.0-2017-02-05-lts-7.19-9007019.tar.gz
           sha1: d2cfc25f9cda32a25a87d9af68891b2186ee52f9

packages:
- '.'
extra-deps: []

flags: {}

extra-package-dbs: []
```

- run `stack setup`.  [Here](https://pastebin.com/DcgUpAhy) the output of the command

### Stack version

```
$ stack --version
Version 1.4.1, Git revision d145fcf505454fc2ed8e42e6c2f014cb833a2968 x86_64 hpack-0.17.0
```

I got the issue with other resolvers. An issue related to this one:
https://github.com/vacationlabs/haskell-webapps/issues/68
