### ISSUE TITLE
Listing flags in stack.yaml gives "Invalid flag specification"

### ISSUE THREAD

**Issue by leohaskell** [commercialhaskell/stack#3374]
I'd expect listing the flags in `stack.yaml` as in
```yaml
flags:
  library1:
    flag-name1: true
  library2:
    flag-name2: false
```

to has the same effect as
```bash
stack build --flag library1:flag-name1 --flag library2:-flag-name2
```

However, the first one fails with "Invalid flag specification" and wants me to add *library1* and *library2* to the *extra-deps* field, while the second one succeeds.

EDIT: This happens with `stack version 1.5.1` on Windows, and I'll try it on Linux too.
