### ISSUE TITLE
Missing Library primitive-memops.h

### ISSUE THREAD

**Issue by wpoosanguansit** [commercialhaskell/stack#3428]
Hi,

I am not entirely sure if this is the right place for this error.  I apologize if it is not.  Any pointer is appreciated.

I am using nix + stack using shell.nix and I do have yml file as below:

```yaml
flags: {}
nix:
  #path: []
  add-gc-roots: true
  nix-shell-options: []
  enable: true
  pure: true
  shell-file: shell.nix
extra-deps:
- base-compat-0.9.1
- bytestring-builder-0.10.8.1.0
- conduit-extra-1.1.13.2
- fast-logger-2.4.6
- aeson-1.2.1.0
- markdown-unlit-0.4.0
- jose-0.5.0.5
- monad-time-0.2
- servant-0.11
- servant-server-0.11
- servant-client-0.11
- servant-auth-0.2.7.0
- servant-auth-server-0.3.0.0
- servant-auth-client-0.2.7.1
- unix-time-0.3.7
- wai-3.2.1.1
- wai-extra-3.0.17
- wai-logger-2.3.0
- http-api-data-0.3.7.1
- fail-4.9.0.0
- mtl-2.2.1
- attoparsec-iso8601-1.0.0.0
- cabal-doctest-1.0.2
- vector-0.12.0.1
resolver: lts-9.2  
```

The error is:

Configuring primitive-0.6.2.0...
    Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2: Missing dependency on a foreign
    library:
    * Missing (or bad) header file: primitive-memops.h

I did have primitive lib installed as:

sudo apt-get install libghc-primitive-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libghc-primitive-dev is already the newest version (0.6.1.0-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgrade

Thank you for your help.
