### ISSUE TITLE
Supporting additional compilers

### ISSUE THREAD

**Issue by jprider63** [commercialhaskell/stack#3517]
Is there documentation on how to create compiler packages that integrate with stack? Something similar to how @tolysz packages GHCJS? 

I'm interested in using stack to create stable compilation for cross compiling to aarch64. @angerman already has some cross-compiling [bindists](http://hackage.mobilehaskell.org/). These require the packages provided in [head.hackage](http://head.hackage.haskell.org/). Is it feasible to package these together to offer stable cross compilation?

**Comment by mgsloan** [comment]
You can point stack at custom GHC bindists via https://docs.haskellstack.org/en/stable/yaml_configuration/#setup-info

Pretty sure you can use the [package-indices](https://docs.haskellstack.org/en/stable/yaml_configuration/#package-indices) option to point at the other package set.  Not sure exactly what the config would look like.  Please post it up here and maybe also elsewhere if you get it worked out.

**Comment by borsboom** [comment]
I'm somewhat struggling in this area right now as well.  https://github.com/tolysz/prepare-ghcjs has info on how @tolysz builds packages, in case that's of any help.

**Comment by angerman** [comment]
Not sure if I can help, as I'm currently not a heavy user of stack. A few things to note though:
- the bindists will soon move away from the `configure && make install` approach and towards a relocatable install package (e.g. unpack and run `bin/ghc`). There are some caveats here, but I hope that this will at least work on macOS and linux reliably. *This is because the current binary-dist logic is tailored heavily towards stage2 (host == target) compilers, and not really towards cross compilers.*
- the bindists implicitly depend on their toolchains. This has been abstracted a bit via the [toolchain-wrapper](http://github.com/zw3rk/toolchain-wrapper)s.  A lot of that is only there to ensure that `$triple-PROG` is called, instead of just `PROG`. Or pass flats to the program (e.g. `--cross-compile` to `hsc2hs`).
- @Tehnix, provided an install script in mobilehaskell/hackage-overlay#4, which might help for some inspiration?
- hackage overlays are essentially hackage indices, with a set of patched applied to a few known packages. `head.hackage` currently has patches for the Semigroup-Monoid-Proposal changes in HEAD. And the `hackage.mobilehaskell` overlay provides patches specific to cross compilation (e.g. zlib), while waiting for changes to be upstreamed. Stackage might have a different approach to this.
I'm not absolutely sure about mix and match of overlays. There is certainly an issue if multiple overlays contain patches to the same package.

**Comment by Tehnix** [comment]
Anything I can do to help!

It would also seem that `setup-info` would need to be able to support more fields. We could probably get the GHC distribution with the `ghc` field, but would be missing things @angerman mentions that the toolchain-wrapper currently handles.

Honestly, it would be super neat to be able to point to a specific compiler with stack that'd take care of all my (admittedly quick) script currently does. Just a lot of path juggling tbh.

**Comment by mgsloan** [comment]
@Tehnix Certainly a PR adding support for these additional fields would be greatly appreciated!

**Comment by jprider63** [comment]
I'm not sure if this is correct, but I've added the following to my `stack.yaml`:

```
resolver: lts-9.10

setup-info:
  ghc:
    aarch64-apple-ios:
      8.3.20171002:
        url: http://hackage.mobilehaskell.org/x86_64-apple-darwin/aa5f532d20/ghc-8.3.20171020-aarch64-apple-ios.tar.xz

package-indices:
- name: Hackage
  download-prefix: http://hackage.haskell.org/package/
  http: http://hackage.haskell.org/
- name: Hackage Head
  download-prefix: http://head.hackage.haskell.org/package/
  http: http://head.hackage.haskell.org/01-index.tar.gz
```

This gives me [link errors](http://lpaste.net/7983367626485137408) complaining about the wrong architecture. 

I tried adding some of the flags @angerman mentioned via `ghc-options`, but haven't had much luck. 

```
resolver: lts-9.10

ghc-options:
  "*": "-pgml xcrun -optl --sdk iphoneos ld -arch arm64"

setup-info:
  ghc:
    aarch64-apple-ios:
      8.3.20171020:
        url: http://hackage.mobilehaskell.org/x86_64-apple-darwin/aa5f532d20/ghc-8.3.20171020-aarch64-apple-ios.tar.xz
# url: http://hackage.mobilehaskell.org/x86_64-apple-darwin/aa5f532d20/ghc-8.3.20171002-aarch64-apple-ios.tar.xz

# compiler: ghc-8.3.20171020
# compiler-check: match-exact

package-indices:
- name: Hackage
  download-prefix: http://hackage.haskell.org/package/
  http: http://hackage.haskell.org/
- name: Hackage Head
  download-prefix: http://head.hackage.haskell.org/package/
  http: http://head.hackage.haskell.org/01-index.tar.gz
```

This results in [errors](http://lpaste.net/1127293950147690496) since the flags aren't formatted properly. Does this look like the right direction?
