### ISSUE TITLE
Specifying snapshot resolvers inline in stack.yaml

### ISSUE THREAD

**Issue by quasicomputational** [commercialhaskell/stack#3561]
With the upcoming release, now we can define our own custom snapshots, e.g.:

```
stack.yaml:
  resolver: foo.yaml
  packages: [foo, bar, baz]
foo.yaml:
  resolver: lts-9.0
  packages: [foo-0.1]
```

I think it'd be nice to be able to inline the resolver as an object in stack.yaml, since I suspect that there'll be strong ties between the local package sets and the snapshot/resolver (e.g., needing to change ghc-options on old LTSes, some local packages known not to work on some GHC versions). Also, the common case is going to be one stack.yaml and one resolver. 

So I'd like something like this:

```
stack.yaml:
  resolver:
    resolver: lts-9.0
    packages: [foo-0.1]
  packages: [foo, bar, baz]
```
