### ISSUE TITLE
Suggested package names repeated

### ISSUE THREAD

**Issue by tfausak** [commercialhaskell/stack#3562]
I accidentally put a package identifier that doesn't exist into my `stack.yaml` and got some interesting output: 

> The following package identifiers were not found in your indices: servant-foreign-0
> Perhaps you meant servant-foreign, servant-foreign, servant-foreign, servant-foreign, servant-foreign, servant-foreign, servant-foreign, servant-foreign, servant-foreign, or servant-foreign?

😆 

``` sh
$ stack --version
Version 1.5.1 x86_64 hpack-0.17.1
```

``` yaml
# stack.yaml
resolver: lts-9.0
extra-deps: [ servant-foreign-0 ]
```

``` yaml
# package.yaml
name: example
version: 0.0.0
library: { dependencies: servant-foreign }
```
