### ISSUE TITLE
Local extra-dep should not be considered $locals

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#3574]
Using `stack` installed with `--git` on Windows 10 64bit, version:

```
Version 1.6.0, Git revision 46121be1b96465f1164e3f84cafa19c7369da9cc x86_64 hpack-0.18.1
```

Given [stack-bug.zip](https://github.com/commercialhaskell/stack/files/1468752/stack-bug.zip), that defines in the `stack.yaml`:

```
packages:
- location: foo
  extra-deps: true

ghc-options:
  $locals: -bob
```

When compiling `foo` I don't expect the flag `-bob` to be applied as `foo` is an extra-dep, and thus not a local package. However, when I `stack build` I get an error about:

```
ghc.EXE: unrecognised flag: -bob
```
