### ISSUE TITLE
Feature Request: no version numbers needed to specify libraries that must be build with other flags

### ISSUE THREAD

**Issue by pjljvandelaar** [commercialhaskell/stack#3583]
As a user, I would like to build some libraries with other flags (due to license issues).
Furthermore, I would like to use the version of these libraries as specified by the resolver.

So instead of specifying (and looking up the version of text in lts-9.13)
```
resolver: lts-9.13
extra-deps:
- text-1.2.2.2
flags: 
  text: 
    integer-simple: true
```
I would like to specify
```
resolver: lts-9.13
extra-deps:
- text
flags: 
  text: 
    integer-simple: true
```
or even better, just the presence of 
```
flags: 
  text: 
    integer-simple: true
```
triggers a rebuild of the text library (expressed in the resolver) 
[and extra-deps are NOT needed]
