### ISSUE TITLE
linux64-gmp4 variant for GHC 8.2.2

### ISSUE THREAD

**Issue by maciej-luminal** [commercialhaskell/stack#3613]
I tried updating my package to GHC 8.2.2 and it failed on CI when building a RHEL6 binary:
```
No information found for ghc-8.2.2.
Supported versions for OS key 'linux64-gmp4': GhcVersion 7.8.4, GhcVersion 7.10.2, GhcVersion 7.10.3, GhcVersion 8.0.1, GhcVersion 8.0.2, GhcVersion 8.2.1
```

I noticed that the last entry for `linux64-gmp4` in [stack-setup-2.yaml](https://github.com/fpco/stackage-content/blob/master/stack/stack-setup-2.yaml) is:

```
8.2.1:
    url: "https://github.com/commercialhaskell/ghc/releases/download/ghc-8.2.1-release/ghc-8.2.1-x86_64-centos67-linux.tar.xz"
    content-length: 119576128
    sha1: b4d7fba53f87f3d11048b56a4190cc2cf5208dc6
```

and that `8.2.2` release doesn't include `centos67` binary anymore. Does it mean that `linux64-gmp4` is not going to be supported?
