### ISSUE TITLE
`stack list-dependencies` gives the same output regardless of target

### ISSUE THREAD

**Issue by dcastro** [commercialhaskell/stack#3695]
### General summary/comments (optional)

When you have a project with multiple test suites (e.g. `unit-a` and `unit-b`), `stack list-dependencies <unit-a | unit-b>` will return a list with all the dependencies of _all_ the test suites. I expected it to return the dependencies of the specified target only.

### Steps to reproduce

    $ stack new mytest && cd mytest && stack init && stack build

Change package.yaml so that it contains 2 test suites with different dependencies:

```yaml
tests:
  unit-a:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - mytest
    - hspec

  unit-b:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - ace
```

```
$ stack list-dependencies mytest:test:unit-a --depth 1
ace 0.6
base 4.10.1.0
hspec 2.4.4
mytest 0.1.0.0

$ stack list-dependencies mytest:test:unit-b --depth 1
ace 0.6
base 4.10.1.0
hspec 2.4.4
mytest 0.1.0.0
```

### Expected

I expected the list of dependencies for `unit-b` to _not_ include `hspec` and `mytest`.
I expected the list of dependencies for `unit-a` to _not_ include `ace`.

```
$ stack list-dependencies mytest:test:unit-a --depth 1
base 4.10.1.0
hspec 2.4.4
mytest 0.1.0.0

$ stack list-dependencies mytest:test:unit-b --depth 1
ace 0.6
base 4.10.1.0
```

### Actual

Stack printed the same list of dependencies for both `unit-a` and `unit-b`, and that list includes the dependencies of both test suites.

### Stack version

```
 $ stack --version
Version 1.6.1, Git revision f25811329bbc40b0c21053a8160c56f923e1201b (5435 commits) x86_64 hpack-0.20.0
```

### Method of installation

Official binary from haskellstack.org
