### ISSUE TITLE
old-style fancy extra-deps (in packages section) are broken in new stack unless you specify 'extra-dep: true'

### ISSUE THREAD

**Issue by kadoban** [commercialhaskell/stack#3728]
Old-style extra-deps that are specified in ```packages``` used to work reliably (as far as I know) without specifying ```extra-dep: true``` in old versions of stack. They no longer seem to work at all (in 1.6.3)

The current behavior is arguably justifiable, but *changing* the behavior that everyone has been using for a long time isn't good. It seems like lots of previously-working stack projects are now broken.

See the output below. Note that the only difference between the two ```stack.yaml``` files is if ```extra-dep: true``` is specified or not (it works if it's specified, doesn't if it's not)

The testcase is on github if you want to play with it https://github.com/kadoban/test-super-proj

### Clone Testcase (and shows version)

```bash
~$ stack --version
Version 1.6.3, Git revision b27e629b8c4ce369e3b8273f04db193b060000db (5454 commits) x86_64 hpack-0.20.0
~$ mkdir -p test/super-proj && git clone https://github.com/kadoban/test-super-proj test/super-proj
[...]
~$ cd test/super-proj
```

### Broken Version

```bash
~/test/super-proj (works-in-stack163)$ git checkout borked-in-stack163 
Switched to branch 'borked-in-stack163'
Your branch is up-to-date with 'origin/borked-in-stack163'.
~/test/super-proj (borked-in-stack163)$ stack clean && stack build && stack exec -- super-proj

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for super-proj-0.1.0.0:
    dep-two must match -any, but the stack configuration has no specified version
needed since super-proj is a build target.
[...]
```

### Extra-dep Specification in Broken Version

```yaml
packages:
- .
- location: ./dep-one
- location:
    git: https://github.com/kadoban/test-dep-two
    commit: fbff976ba58f7c31c6338193acebed2e930c7be1
```

### Working Version

```bash
~/test/super-proj (borked-in-stack163)$ git checkout works-in-stack163-and-old 
Switched to branch 'works-in-stack163-and-old'
Your branch is up-to-date with 'origin/works-in-stack163-and-old'.
~/test/super-proj (works-in-stack163-and-old)$ stack clean && stack build && stack exec -- super-proj
[...builds stuff successfully...]
Completed 2 action(s).
omg it's a string
omg it's another string
```

### Extra-dep Specification in Working Version

```yaml
packages:
- .
- location: ./dep-one
  extra-dep: true
- location:
    git: https://github.com/kadoban/test-dep-two
    commit: fbff976ba58f7c31c6338193acebed2e930c7be1
  extra-dep: true
```

Edit: I confirmed that both of the above versions work fine in stack version 1.5.1. (though the version without the ```extra-dep: true``` gets a warning, it doesn't say anything about it not working in the future, it just says something about the behavior of `stack test`
