### ISSUE TITLE
Failure when working with head.hackage

### ISSUE THREAD

**Issue by TerrorJack** [commercialhaskell/stack#3844]
I'm using `stack-1.6.3` to manage a project which builds with ghc-head and uses head.hackage. The `stack.yaml` file is configured with:

```
resolver: ghc-8.5
allow-newer: true
package-indices:
  - name: head.hackage
    download-prefix: http://head.hackage.haskell.org/package/
    http: http://head.hackage.haskell.org/
    hackage-security:
      keyids:
        - 07c59cb65787dedfaef5bd5f987ceb5f7e5ebf88b904bbd4c5cbdeb2ff71b740
        - 2e8555dde16ebd8df076f1a8ef13b8f14c66bad8eafefd7d9e37d0ed711821fb
        - 8f79fd2389ab2967354407ec852cbe73f2e8635793ac446d09461ffb99527f6e
      key-threshold: 3
  - name: Hackage
    download-prefix: https://hackage.haskell.org/package/
    http: https://hackage.haskell.org/01-index.tar.gz
```

And the above configuration works previously, but has begun to fail with error messages like:

```
Selected mirror http://head.hackage.haskell.org/
Downloading root
Updating package index head.hackage (mirrored at http://head.hackage.haskell.org/) ...SomeRemoteError (HttpExceptionRequest Request {
  host                 = "head.hackage.haskell.org"
  port                 = 80
  secure               = False
  requestHeaders       = [("Accept-Encoding",""),("Cache-Control","no-transform")]
  path                 = "/root.json"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (InternalException (HandshakeFailed (Error_Packet_Parsing "Failed reading: invalid header type: 72\nFrom:\theader\n\n"))))
```

Manually requesting http://head.hackage.haskell.org/root.json in a browser works fine, so I guess something is not right on `stack`'s side. Any clues what's going on under the hood?

**Comment by TerrorJack** [comment]
btw, a temporary workaround is not using hackage security for head.hackage:

```
package-indices:
  - name: head.hackage
    download-prefix: http://head.hackage.haskell.org/package/
    http: http://head.hackage.haskell.org/01-index.tar.gz
  - name: Hackage
    download-prefix: https://hackage.haskell.org/package/
    http: https://hackage.haskell.org/01-index.tar.gz
```
