### ISSUE TITLE
hakyll dependency on nightly is not cached

### ISSUE THREAD

**Issue by st3ll1s** [commercialhaskell/stack#3899]
With the resolver set to `resolver: nightly-2018-03-01`, a package depending on `hakyll` always rebuilds `haddock-library`, `pandoc`, `pandoc-citeproc` and `hakyll`. This does not happen if I set the resolver to `resolver: lts-10.7`. The rebuilds cause significant slowdowns.

Both `pandoc` and `pandoc-citeproc` [seem to be `extra-deps` of hakyll](https://github.com/jaspervdj/hakyll/blob/5dc0b60e6f607fada3d72566dcd1ca4cbfe14c4d/stack.yaml). Maybe this is related?

### Steps to reproduce

1. In `stack.yaml`, set `resolver: nightly-2018-03-01`.
2. Run command `stack build`.
4. Run command `stack build` again.

`package.yaml`: 
```yaml
name: repro

dependencies:
- base >= 4.7 && < 5
- hakyll

library:
  source-dirs: src
```

### Expected

The second `stack build` should not build anything again.

### Actual

`haddock-library`, `pandoc`, `pandoc-citeproc` and `hakyll` are rebuilt.

Output of the second `stack build --verbose`: https://gist.github.com/st3ll1s/3ef40d7d3e5513a31ef031bab129deff

### Stack version

```
root@9aa4322411fe ~# stack --version
Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0
```

### Method of installation

`curl -sSL https://get.haskellstack.org/ | sh`

**Comment by st3ll1s** [comment]
I think this may be caused by `haddock-library` which is a transitive dependency of `hakyll`. Just depending on `haddock-library` suffices to cause rebuilds on every `stack build` invocation.

**Comment by st3ll1s** [comment]
I found a single commit in Haddock that introduces the change: https://github.com/haskell/haddock/commit/3bf3d4c95c3b32ff350e127ee087c85d5bbb24c6.
Before to this commit the rebuilds do not happen.
The latest LTS does not include the above commit which explains why this problem did not occur before.

## Steps to reproduce
Run `stack build` and then `stack build` again.

<details>
<summary markdown="span">
<code>package.yaml</code> as before.
</summary>

```yaml
name: repro

dependencies:
- base >= 4.7 && < 5
- haddock-library

library:
  source-dirs: src
```
</details>

### Build is cached
`stack.yaml`:
```yaml
resolver: nightly-2018-03-07

extra-deps:
  - git: https://github.com/haskell/haddock.git
    commit: 8064353244842c8a5b04d99cd5e6bb6430a9b51c
    subdirs:
      - haddock-library
```

### Build is not cached 
`stack.yaml`:
```yaml
resolver: nightly-2018-03-07

extra-deps:
  - git: https://github.com/haskell/haddock.git
    commit: 3bf3d4c95c3b32ff350e127ee087c85d5bbb24c6
    subdirs:
      - haddock-library
```
