### ISSUE TITLE
Handle case-insensitive flag names WAS Cannot resolve HDBC with time 1.4, even with flags

### ISSUE THREAD

**Issue by hesselink** [commercialhaskell/stack#397]
This is similar to #396, but I can't get it to work even with flags. I can again reproduce with `stack new`, the following `stack.yaml`:

``` yaml
flags: {}
packages:
- '.'
extra-deps:
- HDBC-2.4.0.1
- time-1.4.2
- convertible-1.1.1.0
- utf8-string-1
flags:
  HDBC:
    minTime15: false
resolver: ghc-7.8
```

And adding `HDBC` to the `build-depends` of the cabal file. Issuing `stack build` now gives:

```
While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:
      time: needed (>=1.5 && <1.6), but 1.4.2 found
    needed for package: HDBC-2.4.0.1

--  Failure when adding dependencies:
      HDBC: needed (-any), but couldn't resolve its dependencies
    needed for package: new-template-0.1.0.0
```

Even though, according to the cabal file in `HDBC`, with `minTime15` on `false` it should depend on `time < 1.5`.
