### ISSUE TITLE
Lots of rebuilds when using ghcjs, but why?  --verbose doesn't tell.

### ISSUE THREAD

**Issue by alexanderkjeldaas** [commercialhaskell/stack#4035]
I have a CI server where some code is built using ghc and other using ghcjs.  In the ghcjs case, lots of packages seems to be re-built.

The problem is that `--verbose` doesn't specify *why* a package is being unregistered and rebuilt.  I need to understand why that is, so I can fix the problem.

**Comment by nh2** [comment]
Can you share (parts of) your setup, such as a stack.yaml you're using? It would certainly make it easier to reproduce, and find where more logging is needed if so.

**Comment by alexanderkjeldaas** [comment]
```
resolver: nightly-2018-05-10

packages:
- location: '.'
- location: ...
- .. lots more locations

compiler: ghcjs-0.2.0.9011009_ghc-8.4.1

setup-info:
  ghcjs:
    linux64:
      ghcjs-0.2.1.9007010_ghc-8.0.1:
          url: https://github.com/alexanderkjeldaas/ghcjs/releases/download/ghcjs-v1/ghcjs-0.2.1.9007010_ghc-8.0.1.tar.gz
          sha1: 872dcb8983d2e7181eeea397e5da5affefdc611f
    source:
      ghcjs-0.2.1.9007010_ghc-8.0.1:
          url: https://github.com/alexanderkjeldaas/ghcjs/releases/download/ghcjs-v1-linux/ghcjs-0.2.1.9007010_ghc-8.0.1.tar.gz
          sha1: aff18357b7a7e6be12ff9de9afb8be121f17fa3b
      ghcjs-0.2.0.9011009_ghc-8.4.1:
          url: /opt/ghcjs.tar.gz
              #          url: https://github.com/alexanderkjeldaas/ghcjs/releases/download/ghc-8.4.1-rc2/ghcjs.tar.gz
              #          sha1: 79051ecce5b9d4feaf9107c00178283e062864e1



extra-deps:
# Downgrade uuid to use entropy -0.3.7
# The other packages follow.
- uuid-1.3.12
- git: https://github.com/ghcjs/ghcjs-base.git
  commit: 92bfcf42ffddb9676c4e288efd5750a06c4f4799

allow-newer: true

# Override default flag values for local packages and extra-deps
flags: {}

ghc-options:
 "$everything": -O2 -dedupe

rebuild-ghc-options: true
apply-ghc-options: everything

# Extra package databases containing global packages
extra-package-dbs: []
```
