### ISSUE TITLE
Error using its-12.0

### ISSUE THREAD

**Issue by wpoosanguansit** [commercialhaskell/stack#4143]
I am using its-12.0 and I am having the following error:

```
Downloading lts-12.0 build plan ...
HttpExceptionRequest Request {
  host                 = "raw.githubusercontent.com"
  port                 = 443
  secure               = True
  requestHeaders       = [("User-Agent","The Haskell Stack")]
  path                 = "/fpco/lts-haskell/master//lts-12.0.yaml"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (InternalException (HandshakeFailed (Error_Protocol ("certificate rejected: security: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)",True,CertificateUnknown))))
```

I am using:

Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2

on MacOS High Sierra.

content of the file:

```
flags: {}
nix:
  #path: []
  add-gc-roots: true
  nix-shell-options: []
  enable: true 
  pure: true
  shell-file: shell.nix
extra-deps:
- hjson-query-1.0.2
- blaze-0.0.2
- bytestring-0.10.8.1
- data-memocombinators-0.5.1
- zlib-0.6.1.2
- bound-2
- hashable-1.2.5.0
- hashable-extras-0.2.3
- comonad-5 
- lifted-async-0.9.1.1
- say-0.1.0.0
- base-4.9.1.0
- cabal-doctest-1.0.6
- diagrams-1.4
- diagrams-lib-1.4.2.3
- diagrams-svg-1.4.2
- diagrams-contrib-1.4.3
- diagrams-core-1.4.1.1
- diagrams-solve-0.1.1
- dual-tree-0.2.2
- cubicbezier-0.6.0.5
- mfsolve-0.3.2.0
- fast-math-1.0.2
- hjson-1.3.2
resolver: lts-12.0
allow-newer: true
```

Thanks for your help.
