### ISSUE TITLE
Stack build not sharing HTTP library

### ISSUE THREAD

**Issue by 3noch** [commercialhaskell/stack#421]
```
> stack build
filelock-0.1.0.1: configure
HTTP-4000.2.19: configure
filelock-0.1.0.1: build
HTTP-4000.2.19: build
filelock-0.1.0.1: install
HTTP-4000.2.19: install
...
```

With `stack.yaml`:
```yaml
packages:
- build
- HsLibrary/Hs
extra-deps:
- filelock-0.1.0.1
resolver: lts-2.14
```

I've confirmed that `<repo>/.stack-work/install/x86_64-windows/lts-2.14/7.8.4/lib/x86_64-windows-ghc-7.8.4/HTTP-4000.2.19` does in fact exist. However HTTP is pinned to version 4000.2.19 in LTS 2.14.

Why is it not installing at a user level?
