### ISSUE TITLE
Git dependencies don't override the original ones in custom snapshots

### ISSUE THREAD

**Issue by nikita-volkov** [commercialhaskell/stack#4289]
### General summary

In my custom snapshot I override the "stm" package. Here's how:

```yaml
resolver: lts-12.2
name: metrix-snapshot
packages:
- {git: "https://github.com/haskell/stm", commit: "4f63bbc"}
```

When I use it in my project, it still installs the "stm" package coming from "lts-12.2", not the one that I specify. Only specifying in the "extra-deps" of the project does solve the issue. 

### Stack version

```
stack --version
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2
```
