### ISSUE TITLE
Switch to dictionary instead of list in "extra-deps" and "packages"

### ISSUE THREAD

**Issue by nikita-volkov** [commercialhaskell/stack#4290]
E.g.,

```yaml
extra-deps:
  stm: {git: "https://github.com/haskell/stm", commit: "4f63bbc"}
  transformers: 0.5.0.1
  rocket-launcher: /home/crazy-professor/repos/rocket-launcher
```

This would allow to override the existing settings. And as a part of it would be a solution to the following issue: https://github.com/commercialhaskell/stack/issues/4289
