### ISSUE TITLE
No cabal file found for Archive

### ISSUE THREAD

**Issue by waddlaw** [commercialhaskell/stack#4292]
### Steps to reproduce

1. create new project.

```sh
$ stack new sample
$ cd sample
```

2. edit `stack.yaml` (add `extra-deps`)

```sh
$ cat stack.yaml
resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/12/9.yaml

packages:
- .
extra-deps:
- github: fpco/store
  commit: 247f2863bed0f5c1003ab835075b6dcafb9aa773
```

3. build project

```sh
$ stack build
No cabal file found for Archive from https://github.com/fpco/store/archive/247f2863bed0f5c1003ab835075b6dcafb9aa773.tar.gz
```

Some packages will succeed.(ex. `cassava`)

```yaml
extra-deps:
- git: https://github.com/haskell-hvr/cassava.git
  commit: 151f74b976ce93c59e938ae130324bec53ac8c92
# - github: fpco/store
#   commit: 247f2863bed0f5c1003ab835075b6dcafb9aa773
```

### Stack version

```
$ stack --version
Version 1.10.0, Git revision 388232c3f3ae350e384b2e41c0c11606fd06b69e (6449 commits) x86_64 hpack-0.30.0
```
