### ISSUE TITLE
ghc-options not passed to ghc

### ISSUE THREAD

**Issue by notestaff** [commercialhaskell/stack#4548]
I want stack to always pass certain options to ghc.  I've created config.yaml as follows:

```yaml
extra-path:
- /data/mc3/envs/new-stk-env/bin
extra-lib-dirs:
- /data/mc3/envs/new-stk-env/lib
extra-include-dirs:
- /data/mc3/envs/new-stk-env/include
apply-ghc-options: everything
ghc-options:
  $everything: -v -optl-L/data/mc3/envs/new-stk-env/lib -optl-Wl,-rpath,/data/mc3/envs/new-stk-env/lib -optl-lpthread
rebuild-ghc-options: true
```

But stack still sometimes runs ghc without these options, leading to errors:

```
Progress 139/208

--  While building package optparse-applicative-0.14.3.0 using:
      /data/sroot02/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.2.0.1_ghc-8.4.4 --builddir=.stack-work/dist/x86_64-linux/Caba\
l-2.2.0.1 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /data/sw/git-annex-7.20181211/.stack-work/logs/optparse-applicative-0.14.3.0.log
```

Is there a way to make sure the path to the gmp library is _always_ passed on?
