### ISSUE TITLE
Stack build (Haskell) cannot find any module in the src directory.

### ISSUE THREAD

**Issue by KeesBleijenberg** [commercialhaskell/stack#4553]
If I import module XX  in Main.hs from the src directory, I always get: Could not find module XX
I've purged .stack-work, but no luck. In Main.hs I import ProgSettings and I get the error message.
I tried to add build-depends in packages.yaml, but it didn't work. I always get: Ignoring unrecognized field $.library.build-depends.?
I'am using stack 1.9.3 on Ubuntu. Ghc version: 8.2.2 What can I do?

Kees

The directory structure:

```
-- app
      Main.hs
-- src
      ProgSettings.hs
      ... and more modules
```

packages.yaml:

```yaml
dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies :
    - text
    - megaparsec
    ....

executables:
  freeDB:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:  
    - text
    - async
    ....
    
tests:
  ---    
```
