### ISSUE TITLE
Stack does not apply GHC options in package.yaml

### ISSUE THREAD

**Issue by ad-si** [commercialhaskell/stack#4576]
### General summary/comments

I have defined several GHC `-W` options in my package.yaml.
When I run `ghcid` or `stack ghci` they are applied and I get the corresponding warnings.
However, when I run `stack build` no warnings appear.

Maybe related to https://github.com/commercialhaskell/stack/issues/4526 or https://github.com/commercialhaskell/stack/issues/4548

### Steps to reproduce

1. `stack new test`
2. Add `- -Wall` to `ghc-options` in package.yaml
3. Add `let unused = 123` to src/Lib.hs
4. Run `stack ghci` and obsoerve the warning
5. Run `stack build` and observe **no** warning

### Expected

A `-Wunused-local-binds` warning to appear

### Actual

No warnings whatsoever

The .cabal file contains has the correct `ghc-options`, so it's apparently not a problem of transforming the hpack config into the cabal config.

### Stack version

```
$ stack --version
1.9.3 x86_64
Compiled with:
- hpack-0.31.1
…
```

### Method of installation

```sh
brew install stack
```

**Comment by qrilka** [comment]
@ad-si what section of `package.yaml` did you add `-Wall` to? In the default one there's `ghc-options` for `test-exe` and `tests`, if you want to have a warning for a library source code you should add it into `library` section of `package.yaml`/Cabal file

**Comment by ad-si** [comment]
```yaml
library:
  source-dirs: source

executables:
  tasklite:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -fno-warn-orphans
    dependencies:
      - tasklite
```

That's what it looks like at the moment. I can't see anything about a `ghc-options` field for the `library` section. How do I need to change it?
