### ISSUE TITLE
cannot complete repo info for a non sha1 commit, but it's just a short version?

### ISSUE THREAD

**Issue by silky** [commercialhaskell/stack#4882]
using the latest stack to build a project that has always worked, i now get this error message:

```
09:35 AM noon ∈ src (master*) stack run
Cannot complete repo information for a non SHA1 commit due to non-reproducibility: Git repo at https://github.com/silky/diagrams-pandoc.git, commit d1b122b
```

this is my extra-deps of my `stack.yaml`:

```
extra-deps:
    - git: https://github.com/silky/hakyll-diagrams.git
      commit: 4dd69ad9ce81949b872295ac475453d808399aba

    - git: https://github.com/silky/diagrams-pandoc.git
      commit: d1b122b
```

so the point is that this short-form commit is no-longer valid?
