### ISSUE TITLE
Packages with !include in them don't work with Pantry.

### ISSUE THREAD

**Issue by myShoggoth** [commercialhaskell/stack#4906]
With the new Pantry system taking package dependencies that don't have a top level .cabal or package.yaml file fail.

Example:
```
- git: git@github.com:kim/opentracing.git
  commit: b6e12de671f51f39ea2a9230e43cef2badd993f4
  subdirs:
    - opentracing
    - opentracing-zipkin-common
    - opentracing-zipkin-v2
```
This project has a stack.yaml that references packages, but doesn't have a .cabal or package.yaml file for the top directory.

The error looks like:

`/private/var/folders/6y/_mvyr6tj4px_52pkvychlw1r0000gp/T/hpack-pkg-dir23692/package.yaml: Yaml file not found: /private/var/folders/6y/_mvyr6tj4px_52pkvychlw1r0000gp/T/share/package.yaml`
