### ISSUE TITLE
circleci checkout does not work for docker image lts-14

### ISSUE THREAD

**Issue by nikivazou** [commercialhaskell/stack#5080]
# General summary/comments (optional)

CircleCI with docker image `fpco/stack-build:lts` does not properly `checkout`.

### Steps to reproduce

The `config.yml` starts as follows: 

```
version: 2.1

jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - add_ssh_keys
      - run: git submodule sync
      - run: git submodule update --init
```

### Expected

The fetched submodule is expected to be the one in the branch circle is currently checking. 

### Actual

The `checkout` steps produces the following error 

```
Either git or ssh (required by git to clone through SSH) is not installed in the image. Falling back to CircleCI's native git client but the behavior may be different from official git. If this is an issue, please use an image that has official git and ssh installed.
Enumerating objects: 352, done.
Counting objects: 100% (352/352), done.
Compressing objects: 100% (228/228), done.
Total 72779 (delta 191), reused 186 (delta 82), pack-reused 72427
```

Then `git submodule update --init` brings me the wrong submodule (it brings the submodule specified on the main branch and not the one linked with the current branch).

### Stack version

I tried `lts-14.12`, `lts-14.13`, and `lts`.

### Method of installation

* Other: circleci

### Relevant Links 

- [.circleci/config.yml](https://github.com/ucsd-progsys/liquidhaskell/blob/parse-infix/.circleci/config.yml)
- [circleci output](https://circleci.com/gh/ucsd-progsys/liquidhaskell/3034)
