### ISSUE TITLE
Missing config.yaml specific documentation within file and URL

### ISSUE THREAD

**Issue by conradwt** [commercialhaskell/stack#5166]
### General summary/comments (optional)

Missing `$HOME/.stack/config.yaml` specific documentation within file and URL

### Steps to reproduce

For example:

What keys and values can one use within the config.yaml?  It provides a link to a URL that isn't clear to reader as to what goes within this file other than the templates section.  Can one add the same settings (i.e. keys and values) as the `$HOME/.stack/global-project/stack.yaml` or `<project-dir>/.stack.yaml` file here?  If you're providing a URL, then it should provide a concrete example as to how to use this `config.yaml` file.

```yaml
# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# The following parameters are used by "stack new" to automatically fill fields
# in the cabal config. We recommend uncommenting them and filling them out if
# you intend to use 'stack new'.
# See https://docs.haskellstack.org/en/stable/yaml_configuration/#templates
templates:
  params:
    author-name: name
    author-email: email address
    copyright: copyright information
    github-username: username
# The following parameter specifies stack's output styles; STYLES is a
# colon-delimited sequence of key=value, where 'key' is a style name and
# 'value' is a semicolon-delimited list of 'ANSI' SGR (Select Graphic
# Rendition) control codes (in decimal). Use "stack ls stack-colors --basic"
# to see the current sequence.
# stack-colors: STYLES
```

### Expected

I would expect an example of all such configuration options with supporting examples within the `config.yaml` and/or URL with concrete examples.

### Actual

I only found an example of how to create templates' section.

### Stack version

```
$ stack --version
Version 2.1.3 x86_64 hpack-0.31.2
```

### Method of installation

```bash
sudo port install stack
```
