### ISSUE TITLE
Getting 403 trying to access docs

### ISSUE THREAD

**Issue by fa7ad** [commercialhaskell/stack#5278]
Hi, I tried to access the docs at [this address](https://docs.haskellstack.org/en/stable/maintainers/ghc/)
But, I'm getting a 403.

### Steps to reproduce

1. Open a browser
2. Visit: https://docs.haskellstack.org/en/stable/maintainers/ghc/

### Expected

See the Docs page

### Actual

A HTTP 403 error page.

**Comment by manumc** [comment]
Same here with https://docs.haskellstack.org/ not working either.

```
$ curl -sSL https://docs.haskellstack.org/
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
```

**Comment by mnn** [comment]
Yep. Redirect is working, but that target page is not (`http` is [httpie](https://httpie.org/)):

```yaml
$ http -v --follow --all docs.haskellstack.org
GET / HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: docs.haskellstack.org
User-Agent: HTTPie/2.0.0



HTTP/1.1 302 Moved Temporarily
Connection: keep-alive
Content-Length: 145
Content-Type: text/html
Date: Sat, 25 Apr 2020 06:45:49 GMT
Location: https://docs.haskellstack.org/en/stable/README/
Server: nginx/1.17.8

<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.17.8</center>
</body>
</html>

GET /en/stable/README/ HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: docs.haskellstack.org
User-Agent: HTTPie/2.0.0



HTTP/1.1 403 Forbidden
CF-RAY: 58961a7dadade0d2-IAD
Connection: keep-alive
Content-Length: 151
Content-Type: text/html
Date: Sat, 25 Apr 2020 06:45:50 GMT
Server: nginx/1.17.8
cf-request-id: 0251aee28d0000e0d26705a200000001

<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
```
