### ISSUE TITLE
fail to use a mirror in China

### ISSUE THREAD

**Issue by chenyulue** [commercialhaskell/stack#5299]
According to the [tuna mirror](https://mirror.tuna.tsinghua.edu.cn/help/stackage/) and the [issure #5270](https://github.com/commercialhaskell/stack/issues/5270), my `config.yaml` is 

```yaml
setup-info-locations: 
  - "http://mirrors.tuna.tsinghua.edu.cn/stackage/stack-setup.yaml"
urls:
  latest-snapshot: http://mirrors.tuna.tsinghua.edu.cn/stackage/snapshots.json

package-indices:
  - download-prefix: http://mirrors.tuna.tsinghua.edu.cn/hackage/
    hackage-security:
        keyids:
        - 0a5c7ea47cd1b15f01f5f51a33adda7e655bc0f0b0615baa8e271f4c3351e21d
        - 1ea9ba32c526d1cc91ab5e5bd364ec5e9e8cb67179a471872f6e26f0ae773d42
        - 280b10153a522681163658cb49f632cde3f38d768b736ddbc901d99a1a772833
        - 2a96b1889dc221c17296fcc2bb34b908ca9734376f0f361660200935916ef201
        - 2c6c3627bd6c982990239487f1abd02e08a02e6cf16edb105a8012d444d870c3
        - 51f0161b906011b52c6613376b1ae937670da69322113a246a09f807c62f6921
        - 772e9f4c7db33d251d5c6e357199c819e569d130857dc225549b40845ff0890d
        - aa315286e6ad281ad61182235533c41e806e5a787e0b6d1e7eef3f09d137d2e9
        - fe331502606802feac15e514d9b9ea83fee8b6ffef71335479a2e68d84adc6b0
        key-threshold: 3 # number of keys required

        # ignore expiration date, see https://github.com/commercialhaskell/stack/pull/4614
        ignore-expiry: no
```
When I run `stack setup`, I get the following connection error:

```
Exception while reading snapshot from lts-15.13:
HttpExceptionRequest Request {
  host                 = "raw.githubusercontent.com"
  port                 = 443
  secure               = True
  requestHeaders       = [("User-Agent","Haskell pantry package")]
  path                 = "/commercialhaskell/stackage-snapshots/master/lts/15/13.yaml"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (ConnectionFailure user error (Network.Socket.gai_strerror not supported: 11004))
```

It seems that the tuna mirror is not used when I run `stack setup`.  

After searching the [stack doc](https://docs.haskellstack.org/en/stable/yaml_configuration/#setup-info-locations), I find that `setup-info-locations` uses [stack-setup-2.yaml](https://raw.githubusercontent.com/commercialhaskell/stackage-content/master/stack/stack-setup-2.yaml), and `stack-setup-2.yaml` is different from `stack-setup.yaml` in the contents. I wonder whether it is the missing of `stack-setup-2.yaml` in the tuna mirror that causes the connection failure. And how to solve this problem? Thanks!
