### ISSUE TITLE
Setup exe cache is created in wrong location

### ISSUE THREAD

**Issue by eliaslfox** [commercialhaskell/stack#5302]
### General summary

The setup exe cache is placed in `~/.stack/setup-exe-cache` even when `$STACK_ROOT` is not set to `~/.stack`.

### Steps to reproduce

1. `export STACK_ROOT=~/.local/share/stack`
2. `stack install hpack`
3. `ls ~/.stack`

my global config.yaml
```
save-hackage-creds: false
default-template: simple-hpack

system-ghc: true
nix:
  enable: true
  packages:
    - zlib
    - postgresql
    - llvm
    - ncurses
  add-gc-roots: true
```

### Expected

I expected the cache directory to be created in `~/.local/share/stack`.

### Actual

The cache directory was created in `~/.stack`.

### Stack version

```
$ stack --version
2.3.1 x86_64 hpack-0.33.0
```

### Method of installation

* I am running nixos and installed stack from nix
