### ISSUE TITLE
extra-deps' clones as many times the repository as there are subdirs

### ISSUE THREAD

**Issue by blackheaven** [commercialhaskell/stack#5411]
### General summary/comments (optional)
When I specify, in extra-deps, a repository with many subdirs, the repository is clone many times.

### Steps to reproduce

Build a project with this `package.yml` part:

```
extra-deps:
- git: https://github.com/theam/aws-lambda-haskell-runtime.git
  commit: 6aef017c1621c828a47dc98eae12d84818a8d45c
- git: https://github.com/brendanhay/amazonka.git
  commit: 020bc7bde47bb235e448c76088dc44d6cec13e9b
  subdirs:
    - gen
    - core
    - test
    - examples
    - amazonka
```

### Expected

I expect only one cloning.

### Actual

The repository is cloned once by subdir.

[Partial output](https://gist.github.com/blackheaven/23af3091da8c7ad4b73eb07416edcb7f)

### Stack version

```
$ stack --version
Version 2.3.3, Git revision cb44d51bed48b723a5deb08c3348c0b3ccfc437e x86_64 hpack-0.33.0
```

### Method of installation

```
curl -sSL https://get.haskellstack.org/ | sh
```
