### ISSUE TITLE
Can't clone repo with stack on NixOS

### ISSUE THREAD

**Issue by jvanbruegge** [commercialhaskell/stack#5550]
### General summary/comments (optional)

I have a project where I use not the dependency from stackage, but my own (public) fork from GitHub, configured in stack.yml
Everything works fine in CI, but locally on my NixOS machine, stack fauls

### Steps to reproduce

1. Use this stack.yaml
```
resolver: lts-17.13
packages:
  - .
extra-deps:
  - git: https://github.com/jvanbruegge/openid-connect.git
    commit: 8abba41c5b67429220995ff3127edb8a28e35608
```
2. Try to run `stack build`

### Expected

Normal build process

### Actual

```
Cloning 8abba41c5b67429220995ff3127edb8a28e35608 from https://github.com/jvanbruegge/openid-connect.git
Received ExitFailure 128 when running
Raw command: /nix/store/p9gwh2gv3jp1yfb26i33913gvga1q7c8-git-2.29.3/bin/git clone https://github.com/jvanbruegge/openid-connect.git /run/user/1000/with-repo63157/cloned
Standard error:

Cloning into '/run/user/1000/with-repo63157/cloned'...
fatal: unable to access 'https://github.com/jvanbruegge/openid-connect.git/': SSL certificate problem: unable to get local issuer certificate
```

Runing the given raw command manually works without any issue.

### Stack version

```
$ stack --version
2.7.1 x86_64 hpack-0.34.4
```

### Method of installation

Nix packages, unstable channel
