### ISSUE TITLE
Using a separate repository for private packages

### ISSUE THREAD

**Issue by bnordbo** [commercialhaskell/stack#565]
I have been experimenting with various ways to use stack at our company, trying to find a good workflow.

Quick background: We currently use cabal with local sandboxes and frozen dependencies.  For our private dependencies, we keep sdists on S3 and sync them to local machines[1] using a script that also builds the package index.

One way of dealing with private dependencies in stack is to use git submodules and list the directories in the `packages` section of `stack.yaml`.  Unfortunately not all of my coworkers were fond of this approach, and admittedly it feels a bit clunky.

An alternative approach that feels much nicer is to expose our private packages by adding the repository in `package-indices`.  This requires applying a small patch to allow local URIs, or exposing the repository over HTTP, e.g. using `python -m SimpleHTTPServer`. Consider for example the following `stack.yaml`:

```yaml
flags: {}
package-indices:
  - name: Zakkage
    download-prefix: http://localhost:8000/packages/
    http: http://localhost:8000/00-index.tar.gz
packages:
  - orlop
  - orlop-types
extra-deps:
  - bilge-0.13.0
  - cassandra-util-0.16.0
  - monad-retry-0.2.2
  - types-common-0.4.9
  - types-common-json-0.4.9
  - types-common-cql-0.4.9
  - gundeck-types-0.51.2
  - metrics-core-0.2.1
  - metrics-wai-0.5.1
  - wai-middleware-gunzip-0.0.2
  - wai-utilities-0.13.4
resolver: lts-2.17
```

I would expect this to work because all the packages listed in `extra-deps` are in the "Zakkage" repository, and the rest should be in `lts-2.17`. However, running `stack build` with version 0.1.2.0 fails:

```
~/src/orlop ⫛ feature/stack → stack build
Didn't see aeson-0.8.0.2 in your package indices, updating and trying again
Downloading package index from http://localhost:8000/00-index.tar.gz
Populated index cache.
The following package identifiers were not found in your indices: aeson-0.8.0.2
~/src/orlop ⫛ feature/stack →
```

My hope was that stack would find `aeson` in `lts-2.17` and the packages listed in `extra-deps` in the `Zakkage`, but instead it appears stack only finds packages in the latter. Is there some way of getting this setup to work (without listing _all_ dependencies in `extra-deps`)?

I'm assuming this is not a bug in stack, hence I'm not reporting it as a bug. I am also aware of #445, but my case is somewhat different as my private repository is not a full mirror of Hackage. I am also aware that @drwebb is working on #489 to provide improved documentation on how to deal with these kind of scenarios.

[1] We used to run a local Hackage, but the syncing approach has turned out to be simpler and more robust.
