### ISSUE TITLE
stack can't find existing internal .so when building with stack on musl

### ISSUE THREAD

**Issue by classabbyamp** [commercialhaskell/stack#5683]
### General summary/comments

When building a project with stack, it errors with:

```
pandoc-crossref                  > <command line>: Error loading shared library libHSpandoc-crossref-0.3.12.2-71j0qZmr3NM5uRvdhlMRag-pandoc-crossref-internal-ghc8.10.4.so: No such file or directory (needed by /builddir/pandoc-2.14.0.3/pandoc-crossref-0.3.12.2/.stack-work/dist/x86_64-linux/Cabal-3.2.1.0/build/libHSpandoc-crossref-0.3.12.2-G5TVji8Ep6m3PCEXES5clq-ghc8.10.4.so)
```
but the `.so` file it's looking for exists:
```
$ find masterdir-musl/builddir -name '*internal*.so'
/builddir/pandoc-2.14.0.3/pandoc-crossref-0.3.12.2/.stack-work/dist/x86_64-linux/Cabal-3.2.1.0/build/pandoc-crossref-internal/libHSpandoc-crossref-0.3.12.2-71j0qZmr3NM5uRvdhlMRag-pandoc-crossref-internal-ghc8.10.4.so
```
It does not fail with glibc, only with musl.

### Steps to reproduce

This is being built using void linux's package build system, [xbps-src](https://github.com/void-linux/void-packages), but here is a summary of the steps it takes:
1. install lua5.3, zlib, pkg-config, tar
2. download pandoc v2.14.0.3, pandoc-sidenote v0.20.0.0, monad-gen v0.3.0.1, pandoc-crossref v0.3.12.2, and roman-numerals v0.5.1.5 from hackage and extract them in the same directory (hereafter called `$wrksrc`)
3. 
```sh
STACK_ROOT="$wrksrc/.stack" stack init --system-ghc --skip-ghc-check --force --resolver lts-18.5
# N = number of jobs
STACK_ROOT="$wrksrc/.stack" stack --system-ghc --skip-ghc-check -jN build --flag pandoc:embed_data_files --flag=hslua:system-lua --flag=hslua:pkg-config --verbose 
```

See the [template](https://github.com/classabbyamp/void-packages/blob/pandoc-crossref/srcpkgs/pandoc/template) and [here](https://github.com/void-linux/void-packages/blob/master/common/build-style/haskell-stack.sh) for the exact details.

<details><summary>generated stack.yaml</summary>

```yaml
# This file was automatically generated by 'stack init'
#
# Some commonly used options have been documented as comments in this file.
# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

# Resolver to choose a 'specific' stackage snapshot or a compiler version.
# A snapshot resolver dictates the compiler version and the set of packages
# to be used for project dependencies. For example:
#
# resolver: lts-3.5
# resolver: nightly-2015-09-21
# resolver: ghc-7.10.2
#
# The location of a snapshot can be provided as a file or url. Stack assumes
# a snapshot provided as a file might change, whereas a url resource does not.
#
# resolver: ./custom-snapshot.yaml
# resolver: https://example.com/snapshots/2018-01-01.yaml
resolver: lts-18.5

# User packages to be built.
# Various formats can be used as shown in the example below.
#
# packages:
# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
#   subdirs:
#   - auto-update
#   - wai
packages:
- monad-gen-0.3.0.1
- pandoc-2.14.0.3
- pandoc-crossref-0.3.12.2
- pandoc-sidenote-0.20.0.0
- roman-numerals-0.5.1.5
# Dependency packages to be pulled from upstream that are not in the resolver.
# These entries can reference officially published versions as well as
# forks / in-progress versions pinned to a git hash. For example:
#
# extra-deps:
# - acme-missiles-0.3
# - git: https://github.com/commercialhaskell/stack.git
#   commit: e7b331f14bcffb8367cd58fbfc8b40ec7642100a
#
# extra-deps: []

# Override default flag values for local packages and extra-deps
# flags: {}

# Extra package databases containing global packages
# extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=2.7"
#
# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
```
</details>

### Expected

Build completes successfully.

### Actual

The error described above happens.

[stack log with `--verbose`](https://gist.github.com/classabbyamp/3fd4d65bf40116ae14275fec90e59c89)

### Stack version

<details><summary>stack --version</summary>

```
$ stack --version
2.7.3 x86_64
Compiled with:
- Cabal-3.2.1.0
- Glob-0.10.1
- StateVar-1.2.2
- aeson-1.5.6.0
- annotated-wl-pprint-0.7.0
- ansi-terminal-0.11
- ansi-wl-pprint-0.6.9
- appar-0.1.8
- array-0.5.4.0
- asn1-encoding-0.9.6
- asn1-parse-0.9.5
- asn1-types-0.3.4
- assoc-1.0.2
- async-2.2.3
- attoparsec-0.14.1
- attoparsec-iso8601-1.0.2.0
- auto-update-0.1.6
- base-4.14.1.0
- base-compat-0.11.2
- base-compat-batteries-0.11.2
- base-orphans-0.8.4
- base16-bytestring-1.0.1.0
- base64-bytestring-1.2.1.0
- basement-0.0.12
- bifunctors-5.5.11
- binary-0.8.8.0
- blaze-builder-0.4.2.1
- blaze-html-0.9.1.2
- blaze-markup-0.8.2.8
- byteorder-1.0.4
- bytestring-0.10.12.0
- casa-client-0.0.1
- casa-types-0.0.2
- case-insensitive-1.2.1.0
- cereal-0.5.8.1
- clock-0.8.2
- colour-2.3.6
- comonad-5.0.8
- conduit-1.3.4.1
- conduit-combinators-1.3.0
- conduit-extra-1.3.5
- connection-0.3.1
- constraints-0.13
- containers-0.6.2.1
- contravariant-1.5.5
- cookie-0.4.5
- cpu-0.1.2
- cryptohash-sha256-0.11.102.0
- cryptonite-0.29
- cryptonite-conduit-0.2.2
- data-default-class-0.1.2.0
- data-fix-0.3.2
- deepseq-1.4.4.0
- digest-0.0.1.3
- directory-1.3.6.0
- distributive-0.6.2.1
- dlist-1.0
- easy-file-0.2.2
- echo-0.1.4
- ed25519-0.0.5.0
- either-5.0.1.1
- enclosed-exceptions-1.0.3
- exceptions-0.10.4
- extra-1.7.9
- fast-logger-3.0.5
- file-embed-0.0.14.0
- filelock-0.1.1.5
- filepath-1.4.2.1
- filtrable-0.1.6.0
- fsnotify-0.3.0.1
- generic-deriving-1.14
- ghc-boot-th-8.10.4
- ghc-prim-0.6.1
- hackage-security-0.6.0.1
- hashable-1.3.2.0
- hi-file-parser-0.1.2.0
- hinotify-0.4.1
- hourglass-0.2.12
- hpack-0.34.4
- hpc-0.6.1.0
- http-api-data-0.4.3
- http-client-0.7.8
- http-client-tls-0.3.5.3
- http-conduit-2.3.8
- http-download-0.2.0.0
- http-types-0.12.3
- indexed-traversable-0.1.1
- infer-license-0.2.0
- integer-gmp-1.0.3.0
- integer-logarithms-1.0.3.1
- iproute-1.7.11
- libyaml-0.1.2
- lift-type-0.1.0.1
- lifted-async-0.10.2.1
- lifted-base-0.2.3.12
- lukko-0.1.1.3
- megaparsec-9.1.0
- memory-0.16.0
- microlens-0.4.12.0
- microlens-mtl-0.2.0.1
- microlens-th-0.4.3.10
- mime-types-0.1.0.9
- mintty-0.1.2
- monad-control-1.0.3.1
- monad-logger-0.3.36
- monad-loops-0.4.3
- mono-traversable-1.0.15.1
- mtl-2.2.2
- mustache-2.3.1
- neat-interpolation-0.5.1.2
- network-3.1.2.2
- network-uri-2.6.4.1
- old-locale-1.0.0.7
- old-time-1.1.0.3
- open-browser-0.2.1.0
- optparse-applicative-0.16.1.0
- pantry-0.5.2.3
- parsec-3.1.14.0
- parser-combinators-1.3.0
- path-0.9.0
- path-io-1.6.3
- path-pieces-0.2.1
- pem-0.2.4
- persistent-2.13.1.1
- persistent-sqlite-2.13.0.3
- persistent-template-2.12.0.0
- pretty-1.1.3.6
- primitive-0.7.2.0
- process-1.6.9.0
- profunctors-5.6.2
- project-template-0.2.1.0
- random-1.2.0
- regex-applicative-0.3.4
- regex-applicative-text-0.1.0.1
- resource-pool-0.2.3.2
- resourcet-1.2.4.3
- retry-0.9.0.0
- rio-0.1.21.0
- rio-orphans-0.1.2.0
- rio-prettyprint-0.1.1.0
- rts-1.0
- safe-0.3.19
- safe-exceptions-0.1.7.2
- scientific-0.3.7.0
- semigroupoids-5.3.5
- semigroups-0.19.1
- shelly-1.9.0
- silently-1.2.5.1
- socks-0.6.1
- split-0.2.3.4
- splitmix-0.1.0.3
- stm-2.5.0.0
- stm-chans-3.0.0.4
- streaming-commons-0.2.2.1
- strict-0.4.0.1
- syb-0.7.2.1
- tagged-0.8.6.1
- tar-0.5.1.1
- tar-conduit-0.3.2
- template-haskell-2.16.0.0
- temporary-1.3
- text-1.2.4.1
- text-metrics-0.3.0
- th-abstraction-0.4.2.0
- th-compat-0.1.2
- th-expand-syns-0.4.8.0
- th-lift-0.8.2
- th-lift-instances-0.1.18
- th-reify-many-0.1.9
- these-1.1.1.1
- time-1.9.3
- time-compat-1.9.6
- tls-1.5.5
- transformers-0.5.6.2
- transformers-base-0.4.6
- transformers-compat-0.7
- type-equality-1
- typed-process-0.2.6.1
- unicode-data-0.1.0.1
- unicode-transforms-0.3.8
- unix-2.7.2.2
- unix-compat-0.5.3
- unix-time-0.4.7
- unliftio-0.2.19
- unliftio-core-0.2.0.1
- unordered-containers-0.2.14.0
- uuid-types-1.0.5
- vector-0.12.3.0
- vector-algorithms-0.8.0.4
- x509-1.7.5
- x509-store-1.6.7
- x509-system-1.6.6
- x509-validation-1.6.11
- yaml-0.11.5.0
- zip-archive-0.4.1
- zlib-0.6.2.3

Warning: this is an unsupported build that may use different versions of
dependencies and GHC than the officially released binaries, and therefore may
not behave identically.  If you encounter problems, please try the latest
official build by running 'stack upgrade --force-download'.
```
</details>

### Method of installation

Distro package (void linux)

### Other info

see also https://github.com/lierdakil/pandoc-crossref/issues/342 and https://github.com/void-linux/void-packages/pull/35658
