### ISSUE TITLE
Commit stack*.yaml.lock files.

### ISSUE THREAD

**Issue by philderbeast** [commercialhaskell/stack#5799]
Can we please stop ignoring stack's lock files? The [docs](https://docs.haskellstack.org/en/stable/lock_files/) say these can be put in source control and help make builds more reproducible.

https://github.com/commercialhaskell/stack/blob/8bf6a5afd779c4120c25c6ab5f20d1d5581d8994/.gitignore#L30

**Comment by mpilgrem** [comment]
Without commenting on the merits or demerits, there is an existing issue which discusses this -  https://github.com/commercialhaskell/stack/issues/4795 - and it looks like there were arguments for and against. Can you add your perspective to that discussion?

**Comment by philderbeast** [comment]
Thanks for the link to the previous discussion that seems to be in favour overall with some caution around libraries and CI builds. For my own tastes, reproducibility is top of the list and for my own packages I use something like the following for CI builds:

```
> tree -L 2 stack
stack
├── stack-8.0.2.yaml
├── stack-8.0.2.yaml.lock
├── stack-8.10.7.yaml
├── stack-8.10.7.yaml.lock
├── stack-8.2.2.yaml
├── stack-8.2.2.yaml.lock
├── stack-8.4.4.yaml
├── stack-8.4.4.yaml.lock
├── stack-8.6.5.yaml
├── stack-8.6.5.yaml.lock
├── stack-8.8.4.yaml
├── stack-8.8.4.yaml.lock
├── stack-9.0.2.yaml
├── stack-9.0.2.yaml.lock
├── stack-9.2.3.yaml
└── stack-9.2.3.yaml.lock
```

```yaml
name: stack

on:
  push:
  pull_request:

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.6"]
        ghc:
          - "8.0.2"
          - "8.2.2"
          - "8.4.4"
          - "8.6.5"
          - "8.8.4"
          - "8.10.7"
          - "9.0.2"
          - "9.2.3"

    steps:
      - uses: actions/checkout@v3

      - name: Setup Stack
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
          enable-stack: true
          stack-version: "latest"

      - name: Cache ~/.stack and .stack-work
        uses: actions/cache@v3
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack-${{ hashFiles('**/*.cabal', './stack/stack-${{ matrix.ghc }}.yaml', './stack/stack-${{ matrix.ghc }}.yaml.lock') }}

      - name: Build
        run: stack test --no-run-tests --no-terminal --stack-yaml=./stack/stack-${{ matrix.ghc }}.yaml

      - name: Test
        run: stack test --no-terminal --test-arguments "--color=always" --stack-yaml=./stack/stack-${{ matrix.ghc }}.yaml
```
