### ISSUE TITLE
GHC error when building XMonad with Stack: Bad interface file. Something is amiss; requested module differs from name found in the interface file

### ISSUE THREAD

**Issue by mattweissel** [commercialhaskell/stack#5954]
Copied from a post I made on StackOverflow about Stack -- https://stackoverflow.com/questions/74524194/ghc-error-when-building-xmonad-with-stack-bad-interface-file-something-is-amis. It was suggested by a user in that thread that this could be an issue with Stack because the two hashes referenced in the error message are different, but they should not be?

Below is a transcript of the StackOverflow post.

## GHC error when building XMonad with Stack: Bad interface file. Something is amiss; requested module differs from name found in the interface file

OS: linux gentoo 6.0.9

I am attempting to build a custom version of XMonad using Stack and a build script I wrote, which is closely based on [this one here](https://github.com/xmonad/xmonad-testing/blob/master/build-scripts/build-with-stack.sh). 

`build.sh`:
```
#!/bin/sh
SRC_DIR=$HOME/.config/xmonad
EXE_DIR=$HOME/.local/bin
EXE_NAME=xmonad
######################
unset STACK_YAML
cd $SRC_DIR
stack build 2>.log
ln -f -T $(stack exec -- $EXE_NAME) $EXE_DIR/$EXE_NAME 2>.log
rm ./src/$EXE_NAME.hi ./src/$EXE_NAME.o 2>/dev/null
```
The `stack build` invocation above fails to compile a module that I wrote called `Prompt.Man` (not to be confused by `XMonad.Prompt.Man`, which I did not write) that previously compiled fine, and I do not understand the GHC error at all; when I try looking at the file the error references (`XMonad/Actions/OnScreen.dyn_hi`), it is a binary.

`.log`:
```
Building executable 'xmonad-vem:xmobar'.
Other executables with the same name might be overwritten: 'xmobar:xmobar'.

Building executable 'xmonad-vem:xmonad'.
Other executables with the same name might be overwritten: 'xmonad:xmonad'.

Building all executables for `xmonad-vem' once. After a successful build of all of them, only specified executables will be rebuilt.
xmonad-vem> configure (exe)
xmonad-vem> Configuring xmonad-vem-0.3...
xmonad-vem> build (exe)
xmonad-vem> Preprocessing executable 'xmobar' for xmonad-vem-0.3..
xmonad-vem> Building executable 'xmobar' for xmonad-vem-0.3..
xmonad-vem> [9 of 9] Compiling Prompt.Man
xmonad-vem> 
xmonad-vem> /home/myuser/.config/xmonad/src/Prompt/Man.hs:9:1: error:
xmonad-vem>     Bad interface file: /home/myuser/.config/xmonad/.stack-work/install/x86_64-linux-tinfo6/11f8cebbee3588011a80cb3a0acfb83ab68c1e233a64bf2f944fbcae91e1b2fb/8.10.6/lib/x86_64-linux-ghc-8.10.6/xmonad-contrib-0.17.0-KtuI6PQ7yCQKkNv0hd26Wj/XMonad/Actions/OnScreen.dyn_hi
xmonad-vem>         Something is amiss; requested module  xmonad-contrib-0.17.0:XMonad.Actions.OnScreen differs from name found in the interface file xmonad-contrib-0.17.0-Jq55vblrWW56gRIiMssDFv:XMonad.Actions.OnScreen (if these names look the same, try again with -dppr-debug)
xmonad-vem>   |
xmonad-vem> 9 | import XMonad.Actions.OnScreen (onlyOnScreen)
xmonad-vem>   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

--  While building package xmonad-vem-0.3 (scroll up to its section to see the error) using:
      /home/myuser/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.6 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.1.0 build exe:xmobar exe:xmonad --ghc-options ""
    Process exited with code: ExitFailure 1
```
Adding the flag `-dppr-debug` to `ghc-opts` in `package.yaml` yields the exact same error message upon attempt to rebuild. 

I've also tried deleting my `.stack` and `.stack-work` directories and then re-running as a hopeless attempt to see if that fixes anything, to no avail.

What is causing this error, and how can I resolve it?

Not sure what else you need from me, just let me know in the comments. I will include my Stack config as well, if that is useful.

`stack.yaml`:
```
resolver: lts-18.7
packages:
  - .
  - /var/cache/distfiles/xmobar-0.44.1
  - /var/cache/distfiles/xmonad-0.17.0
  - /var/cache/distfiles/xmonad-contrib-0.17.0
extra-deps: []
flags:
  xmobar:
    with_xpm: false
    with_threaded: false
    with_xft: true
    with_rtsopts: false
    with_alsa: true
    with_mpd: false
    with_weather: false
    with_dbus: false
    with_mpris: false
    with_inotify: false
    with_nl80211: false
    with_iwlib: false
    with_datezone: false
    with_uvmeter: false
    with_kraken: false
arch: x86_64
```
