### ISSUE TITLE
How to suppress annoying warning message

### ISSUE THREAD

**Issue by hyunsooda** [commercialhaskell/stack#6072]
### Stack version
Version 2.9.3, Git revision 6cf638947a863f49857f9cfbf72a38a48b183e7e x86_64 hpack-0.35.1

Hello,

A warning message "SubLibrary dependency is not supported, this will almost certainly fail" appears when the project gets built and tested (i.e., `stack build` and `stack test`).
Can you please help me understand the meaning of this message and guide me on how to suppress it?

My `package.yml` structure is as follows:
```yaml
internal-libraries:
  my-lib:
     ...

executable:
  my-exe:
     dependencies:
        - my-lib
        -  ...

tests:
  my-test:
     dependencies:
        - my-lib
        - ...
```

Thank you.
