### ISSUE TITLE
`stack build --system-ghc` fails on ubuntu-20.04 GHA runner with GHC 7.10.3

### ISSUE THREAD

**Issue by andreasabel** [commercialhaskell/stack#6124]
Looks like the stack-generated `setup.hs` does not build with GHC 7.10.3 due to some CPP macro issues:
https://github.com/josefs/STMonadTrans/actions/runs/5011745635/jobs/8982896507#step:6:1
```
stack build --system-ghc --dependencies-only
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}

/home/runner/.stack/setup-exe-src/setup-shim-SvXsv1f_.hs:5:0:
     error: missing binary operator before token "("
        5 | #if MIN_VERSION_Cabal(3,8,1)
          | 

Error: [S-637[4](https://github.com/josefs/STMonadTrans/actions/runs/5011745635/jobs/8982896507#step:6:5)]
       While building simple Setup.hs (scroll up to its section to see the error) using:
       /usr/local/.ghcup/ghc/7.10.3/bin/ghc-7.10.3 -rtsopts -threaded -clear-package-db -global-package-db -hide-all-packages -package base -main-is StackSetupShim.mainOverride -package Cabal-1.22.[5](https://github.com/josefs/STMonadTrans/actions/runs/5011745635/jobs/8982896507#step:6:6).0 /home/runner/.stack/setup-exe-src/setup-SvXsv1f_.hs /home/runner/.stack/setup-exe-src/setup-shim-SvXsv1f_.hs -o /home/runner/.stack/setup-exe-cache/x8[6](https://github.com/josefs/STMonadTrans/actions/runs/5011745635/jobs/8982896507#step:6:7)_64-linux/tmp-Cabal-simple_SvXsv1f__1.22.5.0_ghc-[7](https://github.com/josefs/STMonadTrans/actions/runs/5011745635/jobs/8982896507#step:6:8).[10](https://github.com/josefs/STMonadTrans/actions/runs/5011745635/jobs/8982896507#step:6:11).3
       Process exited with code: ExitFailure 1
```
Workflow looks standard; relevant excerpt:
```
...
jobs:
  stack:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include: 
        ...
        - os: ubuntu-20.04
          ghc: 7.10.3
          resolver: lts-6.35

    steps:
    - uses: actions/checkout@v3

    - uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true
        cabal-update: false

    - name: Create stack.yaml
      run: |
        echo "resolver: ${{ matrix.resolver }}" > stack.yaml
        echo "packages: [.]" >> stack.yaml

    - name: Build dependencies
      run: stack build --system-ghc --dependencies-only

    - name: Build
      run: stack build --system-ghc
```

Is this a known problem?
