### ISSUE TITLE
Why does the stack script setup take a long time?

### ISSUE THREAD

**Issue by philderbeast** [commercialhaskell/stack#6588]
I'm updating the GitHub actions for `hpack-dhall` and noticed a slowness related to Stack and its scripts.

```yaml
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.10.3.0"]
        vers:
          - {ghc: "9.8.2", stackage: "nightly-2024-05-18"}

    - uses: haskell-actions/setup@v2
      name: setup GHC and cabal-install
      id: setup
      with:
        ghc-version: ${{ matrix.vers.ghc }}
        cabal-version: ${{ matrix.cabal }}
        enable-stack: true
        stack-version: '2.15.7'
```

Even though I have `stack-2.15.7` installed, here I'm running Updo in script mode, using Stack's scripts.

```yaml
    - name: Updo
      run: GHC_VERSION=${{ matrix.vers.ghc }} STACKAGE_VERSION=${{ matrix.vers.stackage }} \
        make -f project-files.mk cabal.project
```

Why does the following use `Cabal-3.2.1.0` and `ghc-8.10.7` for scripts? The linking seems to be taking a long time, [nearly 10 mins](https://github.com/cabalism/hpack-dhall/actions/runs/9163855687/job/25193865214) and longer than the time it takes to install Dhall from source. I can likely avoid this with Updo by switching to installing its executables and using those instead of its scripts.

```
[1 of 2] Compiling Main             ( /home/runner/.stack/setup-exe-src/setup-HwdwpEmb.hs, /home/runner/.stack/setup-exe-src/setup-HwdwpEmb.o )
[2 of 2] Compiling StackSetupShim   ( /home/runner/.stack/setup-exe-src/setup-shim-HwdwpEmb.hs, /home/runner/.stack/setup-exe-src/setup-shim-HwdwpEmb.o )
Linking /home/runner/.stack/setup-exe-cache/x86_64-linux-tinfo6/tmp-Cabal-simple_HwdwpEmb_3.2.1.0_ghc-8.10.7 ...
```
