### ISSUE TITLE
How to generate `stack.yaml.lock` without  GHC installed?

### ISSUE THREAD

**Issue by sol** [commercialhaskell/stack#6696]
On GitHub Actions, I want to use

    stack test --resolver nightly --lock-file read-write --dry-run

to generate  `stack.yaml.lock`, so that subsequently I can use it as a cache key.

Something along the lines of:

```yaml
- run: stack test --resolver nightly --lock-file read-write --dry-run     # this installs GHC!!!
- uses: actions/cache@v4
  with:
    path: ~/.stack
    key: ${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}
- run: stack test --resolver nightly
```

However, the issue with this is that `--dry-run` still installs GHC. This slows down the build by approximately 2 minutes.

Is GHC necessary to construct `stack.yaml.lock`?  I was under the impression that the required input is only:
- `stack.yaml`
- the YAML description of the corresponding snapshot
- the Hackage index (for `extra-deps`)
