### ISSUE TITLE
Feature request : bump git commit

### ISSUE THREAD

**Issue by alanz** [commercialhaskell/stack#697]
At the moment, a specific commit has to be specified for a dependency, as in

```yaml
packages:
- '.'
- location:
    git: git@github.com:alanz/ghc-mod
    commit: 526714aed7592c6d548ce38e9935bef0a984217b
```

I would like to be able to issue a command something like

```
stack bump ghc-mod wip
```

This would update the commit to reflect the currrent HEAD of the `wip` branch in the `git@github.com:alanz/ghc-mod` repository.

A possible enhancement would be to include a `branch: wip` field to the location, and then

```yaml
stack bump
```

could update all the remote repositories.
