### ISSUE TITLE
Implement global config file for authorship options for `stack new`

### ISSUE THREAD

**Issue by chrisdone** [commercialhaskell/stack#744]
Similar to `.make-package.conf`: http://lpaste.net/1987155439418081280

We can put email, author, default license, copyright, etc. in `~/.stack/stack.yaml`.

The config file can be automatically created, and cleverly populated by some information found from `git config`, if git is available. There should be a note to the user when it is first populated to say that they can edit it, and a note in the `--help` of `stack new` indicating this too.

**Comment by snoyberg** [comment]
Why not just put it in ~/.stack/stack.yaml?

**Comment by chrisdone** [comment]
Works for me, I don't really care what the name is.

**Comment by chrisdone** [comment]
Done this. My `~/.stack/stack.yaml` now looks like this:

```
templates:
  scm-init: git
  params:
    author-email: chrisdone@gmail.com
    author-name: Chris Done
    copyright: 2015 Chris Done
    github-username: chrisdone
    category: Development
```

If it's empty, then when running `stack new` a user will see something like this:

```
$ stack new foo
Downloading template "new-template" to create project "foo" in foo/ ...
The following parameters were needed by the template but not provided: author-email, author-name
You can provide them in /home/chris/.stack/stack.yaml, like this:
templates:
  params:
    author-email: value
    author-name: value
Or you can pass each one as parameters like this:
stack new foo new-template -p "author-email:value" -p "author-name:value"
```

Of course, at least IME, one will run `stack new` loads of times, so one would be far more inclined to pop these details in their config file. But the `-p` flag is available which overrides the config file, e.g. `-p copyright "2015 FP Complete"`.
