### ISSUE TITLE
Private 'packages' dependency in docker setup

### ISSUE THREAD

**Issue by MaxDaten** [commercialhaskell/stack#759]
I'm using the 'location' attribute to refer to a private repository. See this example:

```yaml
flags: {}
resolver: lts-2.20
docker:
  enable: true
packages:
- 'endpoint'
- location:
    git: git@bitbucket.org:myuser/endpoint.git
    commit: 49f2f75170a97fd56aeb9c970385558eb7e07a05
  extra-dep: true
  subdirs:
  - client
  - server
extra-deps: []
```

How can I provide the necessary ssh credentials (incl. `known_hosts` file) for this configuration? I tried:

- `mount: ["/home/myuser/.ssh:/home/stack/.ssh"]`
- `mount: ["/home/myuser/.ssh:/home/myuser/.ssh"]`
- `mount: ["/home/myuser/.ssh:/root/.ssh"]` 

without success. Any hints? I guess the `entrypoint.sh` script kills the mounted `/home/stack/.ssh/` directory in the container?

Thank you.
