### ISSUE TITLE
`stack` not automatically installing `alex` (`build-tools` vs `build-depends`?)

### ISSUE THREAD

**Issue by pseudonom** [commercialhaskell/stack#782]
I may have strange behavioral expectations, but based on:

> How do I get extra build tools?

> stack will automatically install build tools required by your packages or their dependencies, in particular alex and happy.

> from https://github.com/commercialhaskell/stack/wiki/FAQ

I'm expecting `stack build` to get `alex` if necessary. 

Instead, for my project I get

```
language-javascript-0.5.14.2: configure
Progress: 1/14
--  While building package language-javascript-0.5.14.2 using:
    ...
    Process exited with code: ExitFailure 1
    Logs have been written to: .../.stack-work/logs/language-javascript-0.5.14.2.log

    Configuring language-javascript-0.5.14.2...
    Setup.hs: The program 'alex' version >=3.1.4 is required but it could not be
    found.
```

Perhaps because `alex` is specified in `build-tools` rather than build depends? https://github.com/erikd/language-javascript/blob/master/language-javascript.cabal#L41

This is with `Version 0.1.3.1, Git revision 908b04205e6f436d4a5f420b1c6c646ed2b804d7`.

**Comment by snoyberg** [comment]
What does your stack.yaml file look like? I think this feature won't work
with custom and GHC resolvers.

**Comment by pseudonom** [comment]
`stack.yaml`:
```
require-stack-version: ">= 0.1.3.1"

resolver:
  name: frontrowed-2.0
  location: stack-snapshot/frontrowed-2.0.yaml

packages:
  ...
```

`frontrowed-2.0.yaml` is based on `lts-3.0`:

```
compiler: ghc-7.10.2

flags:
  aeson:
    old-locale: false
  time-locale-compat:
    old-locale: false
  text:
    integer-simple: false

packages:
  # Extra dependencies
  ...

  # lts-3.0:
  ...
```
