### ISSUE TITLE
Extensible snapshots

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#863]
I'd like to identify a common syntax for all snapshots to use for markup (LTS, Nightly, and the current custom snapshots), and allow snapshots to extend each other. For example: suppose we're using LTS 3.2, but want to modify the version of aeson to 0.14.0, drop pandoc from the included packages, and switch the compiler from GHC 7.10.2 to GHC 7.10.1. Perhaps this could be accomplished with something like:

```yaml
# Saved in: my-lts-3.2-mod
extends: lts-3.2
compiler: ghc-7.10.1
packages:
- aeson-0.14.0
drop-packages:
- pandoc
flags:
  aeson:
    # Overrides any previous flag definitions for aeson
    some-flag: true
```

Longer term: I'm thinking about trying to streamline all of the snapshot code: have a single syntax for LTS, Nightly, and "custom" snapshots, get rid of the specialness of LTS/Nightly (just make it the default available snapshots, like we do with package indices), and have some kind of fallback approach like package indices have right now.
