### ISSUE TITLE
Missing "--flags=" option from cabal

### ISSUE THREAD

**Issue by varosi** [commercialhaskell/stack#983]
stack 0.1.3.1
I have no way to pass flags to cabal via Stack. 
So I cannot build hmatrix for Windows library.

**Comment by razvan-panda** [comment]
@varosi I think that stack can use the flags option inside the yaml file.

The following config (except the last 4 lines) was generated by running stack init inside hmatrix folder:

```
extra-deps: []
resolver: lts-3.3
flags:
  hmatrix:
    openblas: true
  hmatrix-gsl:
    onlygsl: false
  hmatrix-special:
    safe-cheap: false
  hmatrix-tests:
    gsl: true
packages:
- packages\tests\
- packages\special\
- packages\sparse\
- packages\gsl\
- packages\glpk\
- packages\base\

extra-include-dirs:
- C:\Windows\System32\OpenBLAS-v0.2.14-Win64-int64\include
extra-lib-dirs:
- C:\Windows\System32\OpenBLAS-v0.2.14-Win64-int64\lib
```
