### ISSUE TITLE
Can't reuse dep from monorepo that has a top-level stack.yaml

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#994]
I needed to patch persistent-template in order to bump the Aeson dep: https://github.com/bitemyapp/persistent/

I put this in my stack.yaml

```
- location:
    git: git@github.com:bitemyapp/persistent
    commit: 5cd3ec015c159f2c976590f91f98e564034c9ce1
  extra-dep: true
```

Getting this:

```
$ make ghci
STACK_YAML=../stack.yaml stack ghci tldr-data
Getting project config file from STACK_YAML environment
No .cabal file found in directory /home/callen/work/gordium/.stack-work/downloaded/61f1a338a27db75f649c25fa6545d8dcb20a3a0105826f421ed4c5291e252728.git/
```

Wiki didn't seem to have anything relevant: https://github.com/commercialhaskell/stack/wiki/stack.yaml

Watdo? I don't want to vendor this into our git-tree if possible.

**Comment by borsboom** [comment]
The `stack.yaml` in the persistent repo won't be relevant, because stack only uses the `stack.yaml` in the root of your main project.  I think what you want is something like this (not sure about the exact subdirs you want):

```
- location:
    git: git@github.com:bitemyapp/persistent
    commit: 5cd3ec015c159f2c976590f91f98e564034c9ce1
  extra-dep: true
  subdirs:
    - persistent
    - persistent-postgresql
```
